### ISSUE TITLE
Support Gateway API's GRPCRoute

### ISSUE THREAD

**Issue by ElenaHenderson** [traefik/traefik#10072]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hello,

Is there any plan to support Gateway API's GRPCRoute like defined here: https://gateway-api.sigs.k8s.io/api-types/grpcroute/?

**Comment by nmengin** [comment]
Hello @ElenaHenderson,

Thanks for the question.
We haven't planned to work on it yet, but if it's in the Gateway API specifications, it's definitely an enhancement we could provide.

Please provide more information about your use case.

Thank you so much for your attention and participation.

**Comment by FredrikAugust** [comment]
Hi, if I'm not reading the gateway api spec wrong, it is in the spec now. Would it be possible to add this? Thanks 🌞

**Comment by mmatur** [comment]
Fixed by https://github.com/traefik/traefik/pull/10975

It will be available in the next Traefik minor version v3.2.

If you want to give a try before you can use the [experimental image](https://hub.docker.com/layers/traefik/traefik/experimental-master/images/sha256-8824380c9c5af9846cd35c99044189dff4f2df7bc4b615f79e4e90d792bae988?context=explore).
