### ISSUE TITLE
Pop-up login in requests

### ISSUE THREAD

**Issue by Rbsn-joses** [traefik/traefik#10073]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

give 401 when there is no authentication in request

### What did you see instead?

I have a problem with traefik, I'm using traefik ingress, installation done by helm with basic settings, and for some reason when I try to run it on an endpoint that needs authentication, traefik generates a popup window asking for password and login, this it happens on the frontend, when some endpoint n manages to get the session and popuo appears, I would like to know if there is some configuration that I can use to disable this, such as middleware or in the ingress controller itself.

### What version of Traefik are you using?

V2.5

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

It seems that your issue is related to a configuration issue and the GitHub issue tracker is dedicated to bug and feature requests.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2). 

We will close this issue accordingly.
