### ISSUE TITLE
Traefik beta 3 - Error Logging if dynamic file is wrong

### ISSUE THREAD

**Issue by Cebrain** [traefik/traefik#10135]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Hey,

i am upgraded today from v2 to v3 and had a problem that no Dynamic Rule was loaded through the "providers.file" Directory.
I read the migration document, but forgot that i had the depreciated Whitelist -> IPAllowlist setting in different config files.

The big problem was, i only saw this in the log after switching from INFO to DEBUG that a file/setting was wrong.
So i spend a long time analyzing why no file was loaded and thought there was a problem with the provider setting.

My 2 ideas, 
If there is a single wrong file/setting why no other dynamic file is loaded? In my case one file had an error and no other toml file was loaded from the directory.
Additionally, shouldn't there be an log entry with INFO if such an error happens?

### What did you see instead?

Log was empty and did not show any error

### What version of Traefik are you using?

v3.0.0beta3

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by ldez** [comment]
Hello,

> If there is a single wrong file/setting why no other dynamic file is loaded?

because the file can be organized in a different manner (all the middleware in one file, all the routers in one file,... or other approaches), it's not possible to have a consistent behavior because of this.
So the best approach is the "stop" the provider when an error occurs.
This behavior has not changed between v2 and v3.


> shouldn't there be an log entry with INFO if such an error happens?

It was just a mistake during a merge back, the problem will be fixed by #10136.
