### ISSUE TITLE
how to generate cert chain?

### ISSUE THREAD

**Issue by mingmingshiliyu** [traefik/traefik#10141]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

recently,i found out that when i used server.crt cert file,the browser using https just return the single cert to me,but not containing with ca info,so i integrate ca.crt and server.crt together ,but then the cert auth using curl showed ssl auth fail.how do i deal with it

### What did you see instead?

first time,it's normal but returned no chian cert file.second time since i integrate ca.crt and sever.crt fogether as a cert file,it reported error ssl auth

### What version of Traefik are you using?

latest

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by rtribotte** [comment]
Hello @mingmingshiliyu ,

Thanks for your interest in Traefik,

It seems that your issue is related to a configuration issue that is not directly related to Traefik and the GitHub issue tracker is dedicated to bug and feature requests.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.
