### ISSUE TITLE
WAF middleware

### ISSUE THREAD

**Issue by nmengin** [traefik/traefik#10162]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### Context

A [Pull Request](https://github.com/traefik/traefik/pull/10150) integrating a WAF middleware into Traefik has been opened.

Traefik has never embedded such a feature, and we’d like to discuss this before reviewing the PR itself: a broader design review, at the project level.

### Goal

The goal of this proposal is to gather the community’s opinion (users, contributors, maintainers), to consider a WAF integration in Traefik.

How are you solving the WAF problem today with Traefik?  
Should Traefik provide WAF capabilities? How to do it? What are the use cases?

For the sake of efficiency, we want to time box the discussion to one month.

Thanks in advance for feedback and ideas!

**Comment by jptosso** [comment]
Most important ingress controllers have waf integrations
- https://kubernetes.github.io/ingress-nginx/user-guide/third-party-addons/modsecurity/
- https://www.getambassador.io/docs/edge-stack/latest/howtos/web-application-firewalls/
- Envoy: https://github.com/corazawaf/coraza-proxy-wasm

https://www.cncf.io/blog/2022/09/22/how-to-think-about-securing-kubernetes-with-waf-and-dos-protection/

**Comment by keskad** [comment]
> Perhaps worth of thinking could wasm middleware be implemented to Traefik? 

The generic WASM middleware could potentially make possible to extend Traefik without making the codebase growing bigger, so it would stay lightweight.

**Comment by ldez** [comment]
the plugin technology will not change the syntax, it's not a good answer to the syntax problem.

**Comment by zetaab** [comment]
@ldez partially I do agree with you with the syntax thing. It is quite complex and perhaps worth of visiting the format. However, I have not seen better format as opensource. Actually I have not seen anything else than for instance ready rulesets in case of AWS / cloudflare. The biggest problem with ready rulesets are that all applications will not work with those and sometimes rules needs to be modified. So what I am saying: there can be like few predefined rulesets. However, who will maintain these? Plus then there needs to be way to customise these. Unfortanetly I do not see that could be done in any other way than specifying raw modsecurity config.

In my opinion defining new templating language for WAF should be out of context of Traefik. That is something that traefik cannot fix, or if traefik starts new WAF project then its possible.

**Comment by keskad** [comment]
> the plugin technology will not change the syntax, it's not a good answer to the syntax problem.

Sure! The syntax problem maybe could be addressed by introducing a new format that would be translated into old?

**Comment by juliens** [comment]
I agree that it is increasingly vital to include WAF functionality in Traefik.

Like @ldez, I wonder whether ModSecurity is the optimal solution. Although it offers the possibility of configuring various rules, I think Traefik's approach is inherently simpler.

Like you mention @zetaab, could we envision predefined "rules" that can be easily toggled on and off?
I agree it may not be a perfect fit for everyone, but we can adapt and improve based on the feedback received.

Furthermore, I believe that the discussion surrounding plugins constitutes a separate topic. I am in alignment with the notion that we must thoroughly evaluate the necessity and potential implementation of plugins, whether involving WASM or not. However, it is my suggestion that this discourse be conducted in a separate issue to maintain clarity and focus.

**Comment by zetaab** [comment]
so basically the interface could look like 

```yaml
// CorazaWAF holds the coraza web application firewall middleware configuration.
type CorazaWAF struct {
	// Directives parses the directives from the given string and adds them to the WAF.
	Directives string `json:"directives,omitempty" toml:"directives,omitempty" yaml:"directives,omitempty"`
	// EnabledRules contains enabled WAF rules.
	EnabledRules []string `json:"enabledRules,omitempty" toml:"enabledRules,omitempty" yaml:"enabledRules,omitempty"`
}
```

- CRSEnabled is not included anymore, because as I see it. It can be always included.
- I would still keep Directives in config. Why? Otherwise it is going to be really difficult to develop the rules, this is really useful for developing new rules and verifying those against real services.

Example config could look like:

```
http:
  middlewares:
    waf:
      corazaWAF:
        enabledRules:
        - rule1
        - rule2
        - ...
```

**Comment by jptosso** [comment]
We are talking about hundreds of rules and many required options.
Also, we would like to keep consistency across connectors.

CRS requires tens of directives to setup coraza, default actions to setup blocking mode, tens of options to setup crs and options to prevent false positives.

A default configuration is unreliable and it won't work for most of the cases. That's why directives are required.

**Comment by ldez** [comment]
I think we miss the most important element here: what exactly is WAF? What are those rules and their goal?
(those questions are deliberately naive and rhetorical)

From the point of view of Traefik, WAF rules can be seen as simple router rules.

> If using coraza directives will be a problem, coraza or modsecurity are not the right approach

I agree, that to fit with Traefik, the WAF requirements should be thought of differently.

**Comment by emilevauge** [comment]
First of all, thank you for submiting this [PR](https://github.com/traefik/traefik/pull/10150) 🙏 This opens up the WAF discussion, and I'm happy we shake things up on this :)
I will try to sumarize the different questions raised by this issue:

1.  The ModSecurity Rule Language is complex, but at the same time, it's a de-facto standard, and there is no known (simpler & OSS) alternative
2. Predifined rules set (like [CRS](https://owasp.org/www-project-modsecurity-core-rule-set/)) could be a great option to integrate with Traefik, this would hide the complexity of ModSecurity rules. But @jptosso is saying that 
> A default configuration is unreliable and it won't work for most of the cases. That's why directives are required.
It would be great to give us more technical details on your concerns @jptosso. How would this be unreliable? Isn't it possible to propose predefined rules?
3. The integration implementation raises questions: using yaegi plugins (does not work)? Wasm (not even bootstraped in Traefik)? Included in a middleware? The later option would be the fastest but comes at the cost of including Coraza source code in Traefik, and such tightly coupled components raise a few concerns (versioning, maintenance, etc). 

Any other issues? Any comments?

**Comment by jcchavezs** [comment]
Sorry for being late to the party. First of all, thanks @nmengin for opening up this for discussion. WAF is certainly a must when it comes to security in cloud. As for this being supported in Traefik or not I think the question would be: _does traefik consider L7 protection as a first class concern?_ If the answer is yes then we talk about the existing options.

A WAF is aimed to be the first line of defence in a distributed deployment. That said, CRS is the defacto standard for such purpose with a long experience fighting a varied set of attacks and is the real feature we want to deliver to traefik. Coraza is a robust library writen in golang which has cloud native proxies/gateways as first class concern, hence performance is a key value.

As for the practical concerns in the integration. Yes, seclang is somehow verbose and not super intuitive, **however** most of the users will do 

```yaml
directives:
  - Include my-config.conf
  - Include @owasp_crs/**
```

or

```yaml
directives:
  - SecRuleEngine ON
  - SecDebugLogLevel 5
  - Include @owasp_crs/**
```

When people ask about own ruleset it is very rare that they a. don't use CRS and b. rewrite large sets of rules so I wouldn't worry too much about the verbosity of the config.

In any case, Coraza is not constrained to seclang and we used to support an API for rules (which we closed because it was too early) so a next iteration could implement another way of declaring ruleset, however as @jptosso points out, Coraza (or any other CRS based WAF) depends on several variables which require a fine tuning and CRS does exactly that job so in a way I would say the default configuration for Coraza is `Include @owasp_crs/**`.

With all that said I would agree on not to reinvent the wheel and if sticking to a specific implementation is a concern I am happy to continue the discussion about extensibility in https://github.com/traefik/traefik/issues/9552#issuecomment-1761507509

**Comment by mbuckbee** [comment]
Full disclosure: I’m one of the founders of Wafris (an open-source Web Application Firewall), and we’re currently building a Traefik plugin. 

I'm going to try and answer some questions from further up the thread:

**What's a WAF?**

The spectrum of what people call a WAF goes from "paste these commands into a .htaccess" file up to Cloudflare/Imperva style "point your DNS to us and we'll reject anything bad and only pass you the traffic that passes"

**What general functionality are people looking for?**

Most of the time WAFs do a mix of:

- Threat blocking of things like SQLi, XSS, etc. (the Owasp CRS mentioned is excellent for this, and Coraza looks like a nice way to add that)

- GeoBlocking (hey, maybe we shouldn't do business with North Korea)

- Reputational Blocking (hey, maybe this IP address from a known Eastern European  malware host isn't innocently buying Steam Gift cards off our site)

- RateLimiting/Throttling (hey, maybe we should limit requests to the API by token)

- Dynamically blocking based on request properties (IP, CIDR, User Agent, Paths, etc.)

- Alerting around behavioral changes/anomalies (hey, is it weird that one IP is making 1000x the number of requests than average)

- Virtual Patching (hey, this Log4j thing seems real bad; can we block all attempts to submit text to the site that contains the string 'jndi')

**What about FineTuning and False Positives?**

There were a couple of questions about what was meant by fine-tuning / false positives.

The issues is that there is a considerable gray area between things most WAFs or rulesets like CRS would block and what most web servers and applications would allow. 

We had a client pay a RIDICULOUS amount of money to have a celebrity influencer post a link about their product.  But the PR person who fed them the link to the site copied it from a Word document (because of marketing people), and it contained a trailing encoded CR/LF. 

CR/LFs in URLs are accepted with no issue by web frameworks, etc., but the WAF blocked it as they’re also used in certain header injection attacks. 

Money burning. Fans angry. Client's C-Suite was furious.

The resolution was to write an exception rule on the fly that allowed this (obviously safe) path to work.  

Issues like the above are pretty routine when using a WAF, as you're constantly riding the line of too many false positives vs too lax of rules, letting potential attacks through.

**Rule Change Velocity and Philosophy**

I'm not a Traefik expert, but my sense of the configuration management cadence is that you set things up, and once you're up and going, you're not modifying setups daily. 

I think this is somewhat at odds with a security ops cadence that may have you making dozens of changes daily. A few clients make dozens of modifications daily, mostly banning individually abusive IPs. 

**Are we doing the right thing making a plugin?**

This is my question. We have a very different architecture than Coraza or some other solutions. But also, I see that there was an effort at one point for a Coraza plugin, as well as one for Snapt WAF (that seems defunct).

**Comment by dune73** [comment]
Interesting discussion. OWASP CRS co-lead here, I'm one of the friends of @jptosso and @jcchavezs.

I think @mbuckbee is spot on what false positives can mean in operation. You can not allow this _by default_.

I see the problem of base configuration a bit less dark than @jptosso, CRS is a "generic deny-rules" project after all. The rules are supposed to work everywhere. But they come with a false positive problem. There are various ways to handle this, teaching the the necessary skills is my business case, I have developed commercial software to support enterprise users and bla bla.

But the bottom line is, you can not enable a hard blocking by default on your software. At least not with a strong rule set like CRS. If you are looking for checkbox security, look over to AWS WAF that never produces a false positive and never blocks a skilled attacker.

Within the open source space, you are pretty much limited to engines reading ModSecurity's "SecLang" like the original ModSecurity engine or alternative, more modern implementations like Coraza. As for rules, there is CRS and then very few smaller, more limited alternatives. I'm obviously biased, so you may want to evaluate this yourself.

So what options are viable if you want to bring Coraza / CRS this to traefik:
* Water down the rule set - this is what existing commercial integrators do
* Preconfigure, but don't enable
* Enable, but non-blocking, stick to monitoring
* Enable, but soft-blocking

The soft-blocking is a specialty that CRS allows. CRS is a scoring rule set, requests are only blocked once they hit a certain threshold. You can thus put the WAF in blocking mode and set the threshold very, very high, so it effectively never blocks. Integration would then mean to handle false positives and lower the threshold over multiple iterations. This is the methodology that I teach in my courses.

Beyond SecLang, @mbuckbee points out additional WAF functionality. I do not want to debate what a WAF is and what not. But I think you must be clear, that you are not getting all of this via a single tool. You need to set priorities and develop a plan which features you want to bring to your users. Coraza can probably provide half of the items on @mbuckbee's list. Others will demand other tools or additional development. My advice is to take this step by step and the ability to detect SQLi + XSS + friends should probably be the baseline.

**Comment by jptosso** [comment]
Outstanding contributions, everyone. Thank you @dune73.
I have experience as an enterprise integrator, and one of the biggest struggles is false positive management, even for P1.
I have never seen an application work by default using Coraza and CRS. I also recognize the problem it represents, as patching false positives for applications requires specific knowledge of seclang.

Patching false positives is not disabling rules. It involves ignoring parameters for specific requests and rules, skipping rules categories for certain paths, and more.

I also agree with the Traefik team that we should take a cloud-native approach and make coraza configurations more yaml friendly and less seclang.

Right now, there are informal efforts to move away from seclang. Still, we are far from seeing it, so maybe instead of focusing on how we block, we could take the default approach of CRS and devise a standardized and serializable mechanism to patch false positives.

**Comment by dune73** [comment]
The first informal attempt to move away from SecLang I saw was a paper by Ivan Ristić around 2008. So yes, this makes sense, but don't hold your breath.

Patching false positives: I think it worthwhile to get the terminology right from the start (also in this discussion). False positives are alerts for otherwise benign payloads. You want to tune them away by reconfiguring the WAF, so the WAF no longer triggers alerts for these payloads. The practical process boils down to create so-called Rule Exclusions. A rule exclusion instructs the WAF to not apply a specific rule in a specific situation. Dr. Folini from Switzerland (-> that's me) claims there are 4 canonical types of rule exclusions. Disabling a rule completely is one of the four (-> correcting @jptosso's statement above: patching false positives can be the disabling of rules). A more granular approach can mean to disable a rule for a certain argument on a certain URI. All documented at https://coreruleset.org/docs

Other than that @jptosso is absolutely correct: False positives spoil all the fun. You need skills to tune them away. Free or commercial tuning can easy the pain a very big deal. But don't throw your users into false positive hell via enabling a hard blocking mode by default. See above.

**Comment by geraldcroes** [comment]
Hey everyone, 

it's been one month now that this proposal has been opened and has had a call for comments.

We discussed it during [triage](https://github.com/traefik/contributors-guide/blob/master/issue_triage.md) today, and decided to _not_ embed native WAF support for now.

Our reasoning is that with the upcoming support for [WASM plugins](https://github.com/traefik/traefik/pull/10189) (especially thx to @zetaab efforts) we'll be able to probe usage of different WAFs technologies within traefik before we need to make a stronger call and chose _the_ technology we'd like to embed (if any).

We'll keep the issue opened to keep gathering opinions, but we'll close the [Coraza PR](https://github.com/traefik/traefik/pull/10150) in favor of embedding it as a WASM plugin very soon.

**Comment by david-thrower** [comment]
Hopefully my thinking isn't too far out in left field.

I would consider including a next generation / AI based WAF middleware, something that behaves more like an SPI firewall and can use reinforcement learning to identify a pattern in flagged false positives, false negatives rather than relying on an endless list of rules and heuristics to configure it to allow required traffic. 

I can't remember the name of the project, but I think there is an open source SPI firewall firmware (for open source routers) that uses voluntary crowd sourcing for the data used to train the AI component to identify malicious and impersonated traffic. From what I heard it is quite effective. 

Some content from their repo may be a good starting point for designing the core engine of a middleware like this.

**Comment by dune73** [comment]
I've heard the term "next generation / AI based" WAF for the first time in 2007. There will come the day when this idea really works, but until then, AI based WAFs are a rather shallow promise. Mostly for conceptual reasons.

If traefik wants to set itself apart from the market and place a bet on its ability to deliver on that promise, then good luck. If traefik thinks it's better to differentiate in other areas, then I suggest traefik goes with the simple and proven heuristic approach. The concept may be boring and even stupid when examined from the outside, but there are 20+ years of experience with this and the open source CRS rule set is the dominant player in this field. Almost all the big cloud providers have a CRS offering and that's for a reason.

**Comment by nmengin** [comment]
There is a [plugin](https://plugins.traefik.io/plugins/65f2aea146079255c9ffd1ec/coraza-waf), I close this proposal.
