### ISSUE TITLE
Support gateway api v1

### ISSUE THREAD

**Issue by iFrozenPhoenix** [traefik/traefik#10182]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

As the gateway api progressed the version of the crds moved to v1 and v1alpha is deprecated.
Due to this traefik isn't capable anymore to process gateway api crds as they are all logged as not found.

I'd like to ask to update the implementation so that current versions can be recognized and used, even if not all features are implemented.

**Comment by jspdown** [comment]
Thanks @iFrozenPhoenix for opening this issue. 

There's a clear need in updating this provider. We used to track such efforts in https://github.com/traefik/traefik/issues/9476 (v1beta1)
But since last year, a lot of progress happened. `Gateway`, `GatewayClass`, and `HTTPRoute` have graduated to GA with the `v1` version. Therefore, efforts should instead go in the direction of `v1` support. 

This issue will be used to track effort for bringing support for Kubernetes Gateway API `v1`.

If you or another community member would like to build it, let us know and we will work with you to make sure you have all the information needed so that it can be merged.  

We prefer to work with our community members at the beginning of the design process so that we can make sure that we are aligned and can move quickly with the review and merge process.  Let us know here or create a PR before you start and we will work with you there.

**Comment by ekarlso** [comment]
@mmatur I am trying this patch out and getting

```
gateway=default namespace=shared providerName=kubernetesgateway
2023-11-17T07:48:28Z ERR error="an error occurred while updating gateway status: failed to update Gateway \"default\" status: Gateway.gateway.networking.k8s.io \"default\" is invalid: status.conditions[1]: Duplicate value: map[string]interface {}{\"type\":\"Accepted\"}" gateway=default namespace=shared providerName=kubernetesgateway
```

**Comment by mmatur** [comment]
@ekarlso the issue should be fixed on my [commit](https://github.com/traefik/traefik/pull/10205/commits/72d219eb9ee7c827c52bf7d4f6283a37b4e75fd5)

**Comment by ekarlso** [comment]
@mmatur Thanks, it's working!

**Comment by DokiDoki1103** [comment]
> @mmatur Thanks, it's working!

Hi, any idea on when this be ready for merge ? 🤔

**Comment by ekarlso** [comment]
@mmatur any idea on getting a proper build out the door ?

**Comment by mmatur** [comment]
Closed by https://github.com/traefik/traefik/pull/10205

@ekarlso This docker [image](https://hub.docker.com/layers/traefik/traefik/experimental-v3.0/images/sha256-d14b976874f4fd2635df4f32acda47819757f9ded0d2a8a9b441acc5bc009e51?context=explore) contains the new Gateway API v1 support

**Comment by mguggi** [comment]
@mmatur Why is the Gateway API v1 support not in the official Traefik v3 image? 

With the Helm Chart I've the issue that I can not use this unofficial image because the deployment stops with the following error:
 
`Error: INSTALLATION FAILED: template: traefik/templates/rbac/clusterrole.yaml:48:13: executing "traefik/templates/rbac/clusterrole.yaml" at <semverCompare "<3.0.0-0" (include "imageVersion" $)>: error calling semverCompare: Invalid Semantic Version`

**Comment by mmatur** [comment]
@mguggi because no version has been created for Traefik v3 since the merge of the Gateway API support. 

A new version will be available soon.

If you want to give a try on can use the following [image tag](https://hub.docker.com/layers/traefik/traefik/experimental-v3.0/images/sha256-5af2517270ad6f4c6ce57c64055ba4ec02110f4684f4ff3d75f8f5b80573b56e?context=explore)
