### ISSUE TITLE
Traefik v3 release strategy

### ISSUE THREAD

**Issue by nmengin** [traefik/traefik#10260]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Here are some updates on the Traefik v3.0 front. 

The Release Candidate (RC) is gearing up for its grand entrance, and here is the lowdown on our strategy:

#### Keep It Smooth and Simple

We're committed to making the jump to v3 as seamless as possible. We've heard the feedback and made the necessary adjustments: 
- [Support for both old and new CRD groups in v2.10 ](https://github.com/traefik/traefik/pull/9765)
- [Support the new AllowList middleware in v2.11](https://github.com/traefik/traefik/pull/10249)
- Concerning the new rules syntax, we’ll provide both the old and new ones as well in v3

On top of these preliminary actions, still to ease the migration, we are studying tooling options that would complete the incoming migration guide.
Any other concerns? Reach out in the comments!

#### OpenTelemetry

OpenTelemetry is the next standard for observability and embracing it is a game-changer.
However, configuring Traefik v3 to leverage OpenTelemetry tracing capabilities is incompatible with the former OpenTracing approach in Traefik v2 (due to [new semantic conventions](https://opentelemetry.io/docs/specs/semconv/) and other changes).
Once again, to make a smooth transition, [here is a first migration guide](https://opentelemetry.io/docs/migration/), and we're looking to provide a specific one for traefik.

#### GatewayAPI

It's been a journey since we started[ integrating GatewayAPI in Traefik](https://github.com/traefik/traefik/pull/7416) and we're putting in the final stretch. Stay tuned for more updates!

#### WASM

Many thanks to @zetaab for spearheading the [WASM plugin](https://github.com/traefik/traefik/pull/10189) action. It's in the fast lane to be part of the v3.0.

#### PR Party

Lots of open PR aim [v3.0](https://github.com/traefik/traefik/milestone/20)! Thank you for that, maintainers are doing their best to merge them to close that first RC.

We know you've been eagerly awaiting v3, and we're glad to share this strategy.
Dive into the discussion - we'd love to hear your thoughts!

**Comment by iFrozenPhoenix** [comment]
@nmengin thanks for sharing the latest information.
Concerning the old and new Syntaxes for Rules and the CRD groups I think it would be better to drop the support in 3.0 because it is a breaking change and would therefore be confirm with semantic versioning. Dropping the support for these things at a later point would be difficult, probably earliest with v 4.0.

**Comment by rit001** [comment]
> @nmengin thanks for sharing the latest information. Concerning the old and new Syntaxes for Rules and the CRD groups I think it would be better to drop the support for the old ones in 3.0 because it is a breaking change and would therefore be confirm with semantic versioning. Dropping the support for these things at a later point would be difficult, probably earliest with v 4.0.

Would it not be better to have known labels that can be set to enable/disable the support for the older standard? What their defaults are would not impact my use of Traefik, but being able to move to V3.0 and then toggle such settings would allow me to fully test my migration and then disable the older standards when I am sure that everything is across and updated.

**Comment by iFrozenPhoenix** [comment]
With a new major release breaking changes can occur. I would prefer a clean code base instead of legacy support. This should also increase the awareness to read the release notes and not blindly updating.
Traefik already has many legacy features and it increases the maintenance cost.
So in my opinion, we should help the maintainers to move the project forward.

**Comment by mmatur** [comment]
@iFrozenPhoenix I'm aligned with you. I also prefer clean code over maintaining legacy features. The best scenario would be to drop the old support rule and keep only the new rule syntax. Since we are working on a new major version, it is acceptable to me, and it will be the quickest way to release a final version of Traefik v3.

Given that we have a large community with users exposing many applications through Traefik, changing the rule syntax might require a substantial effort on their part to be compatible with the new syntax in Traefik v3.

That's why I believe it's better to introduce the new routing syntax, deprecate the old one in v3, and make the new syntax the default in Traefik v4.

**Comment by nmengin** [comment]
Hello @iFrozenPhoenix, @rit001,

Thanks for reaching out.

I'm on the same line as @mmatur.

With the other maintainers, we recently scanned the incoming breaking changes to ensure we bring, in v3, only those that are mandatory.
We pay attention to the migration cost and we avoid embedding changes with a big impact on our users' production.
Indeed, we don't want these breaking changes to be a blocker to the adoption of Traefik v3.

For those reasons, as @mmatur said, we have decided to maintain the old rule format (and deprecate it) in v3,  we'll remove it in the future and unplanned v4.

> So in my opinion, we should help the maintainers to move the project forward.

Thank you for that @iFrozenPhoenix  😄

**Comment by Prajithp** [comment]
We have over 1000+ rules in production, and dropping support for old routing rule syntax  in version V3 is quite difficult for us to upgrade since a lot of engineering bandwidth is required to complete this, and it might get delayed due to other feature priorities. I would like to have the old rule syntax deprecated in version V3 and removed in version V4 so that we get enough time to update the rule.

**Comment by nmengin** [comment]
Hello,

Quick update: Maintainers changed their minds and we decided to limit breaking changes to the bare minimum, especially at the dynamic configuration level that matters to users.

As a rule of thumb, we will deprecate options initially slated for removal. This allows for an easy transition from v2 to v3. 
Notably, [traefik.io/v1alpha1 CRDs](https://github.com/traefik/traefik/pull/9600) and the current rule system will remain supported.

Some features, such as the [FastHTTP integration](https://github.com/traefik/traefik/pull/9528), will be deferred to a next minor version to give more time and bring backward compatibility along with it.

However, we will retain some breaking changes in the static configuration, particularly those associated with [Open Telemetry](https://github.com/traefik/traefik/pull/10223).
Clear and comprehensive guidance will be provided in the documentation and traefik logs.

This strategy means more work for maintainers, but a much better upgrade experience for users.

Questions? Drop them in the comments.

**Comment by Zanathoz** [comment]
@nmengin How can I troubleshoot my v2 config easily which breaks during a v3 upgrade? I've read over the breaking changes document several times and scanned my File configurations while commented out the few items that are marked for deprecation, but I'm still getting 404 errors when I try the upgrade. I think my issue lies somewhere in the "Matchers" section called out in the migration site, but I'm not certain. 

While I'm only using Traefik in my homelab I would like to be prepared when 3.0 does eventually drop. It looks like the main site is still mainly geared towards v2 examples and the breaking changes page doesn't give clear examples on how to change an existing configuration. Is there a location I can find v3 examples so I can dig a bit further into my configuration and see what might be breaking during the upgrade?

**Comment by iFrozenPhoenix** [comment]
You can find the migration guide here https://doc.traefik.io/traefik/master/migration/v2-to-v3/
You mention that you are using it for homelab, eventually you can share your v3 config (if it is not too big), otherwise a snippet of something that is not working as expected would be helpful to give you a concrete advice.

Mit freundlichen Grüßen / Kind regards
________________________________

**Comment by Zanathoz** [comment]
> You can find the migration guide here https://doc.traefik.io/traefik/master/migration/v2-to-v3/> […](#)

This is the "breaking changes" document to which I am referring. There are only mentions of changes with no configuration examples akin to the v2 configuration guides. I don't know what's breaking exactly unless I take a very targeted approach to start with nothing and slowly add services back in which could take some time.

**Comment by iFrozenPhoenix** [comment]
Well, this is the same link I mentioned in my reply.
As the traefik team stated breaking changes are limited to a bare minimum (see posts above).
I think the problem is that v3 is still not finished (a short time ago, there were still phases where decisions are made what will be in v3 and how). I would recommend that you be patient a little bit. With the release of v3, v2... versions are not out of support on the next day. But I think it needs a bit more time to finally decide on the details, implement them and than document them.
The current v3 is a beta (and therefore generqlly not recommended for production), so most of the things are already finalized, but details could still shape.

If you REALLY want to change you current runtime config to v3 I would recommend you to use the v2 examples in conjunction with the migration guide. But be prepared that this would still not be final.

Remarks: I'm not part of traefik. This is my personal opinion due to my experiences with v3.

Mit freundlichen Grüßen / Kind regards
________________________________

**Comment by nmengin** [comment]
Traefik v3.0 is released.
I close this issue.
