### ISSUE TITLE
Explain which port traefik must expose to make dnschallenge acme certificate generation work

### ISSUE THREAD

**Issue by YuryHrytsuk** [traefik/traefik#10263]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I expected documentation to explicitly and clearly say which `port` traefik must expose to make `dnschallenge` acme certificate generation work.

**Comment by ldez** [comment]
Hello,

There is no port for the DNS-01 challenge: the DNS challenge will just use the API of your DNS provider to create a TXT record (this is outside of your local network).

The HTTP-01 and TLSAPLN-01 use a port but not the DNS challenge.

**Comment by YuryHrytsuk** [comment]
Hi @ldez,

Thank you for your answer. I still have a simple question: 

> will DNS challenge work if I do NOT expose any port?

**Comment by ldez** [comment]
The DNS challenge doesn't need Traefik to expose a port because the ACME server, to validate the challenge, will communicate with a public DNS server, not Traefik itself.

Doing an ACME challenge requires being able to communicate with the ACME server.
Using a DNS challenge requires being able to communicate with the API of your DNS provider.
So you need to be able to communicate with those 2 elements, but it doesn't require to expose publicly a port.

The DNS-01 challenge doesn't require to expose any port.
