### ISSUE TITLE
Strange behaviour for config-file + directory

### ISSUE THREAD

**Issue by typoworx-de** [traefik/traefik#10343]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Trying to set these traefik.yaml options:
providers.docker.constraints
providers.docker.network

either bs docker-compose.service.command
or
traefik config-directory and sub-file.

None of these solutions work and traefik willl not apply such filters for services that should use that traefik in docker.

Using /traefik.yaml main-config file and setting these options works!
But using the same syntax in /conf.d/my-providers.yaml

will not work.

Even trying to override this using docker.service.command cli-arguments doesn't seem to get recognized.

This behaviour feels very atypic as one would assume other behaviour or at least any notice about that.

### What did you see instead?

all services that use traefik labels (of other stacks)

### What version of Traefik are you using?

traefik:latest and traefik:v2.10 have been tested

### What is your environment & configuration?

```yml
providers:
  file:
    watch: true
    filename:  /traefik.yaml
    directory: /conf.d/
```

### If applicable, please paste the log output in DEBUG level

--

**Comment by ldez** [comment]
Hello,

you cannot use `filename` and `directory` at the same time because the 2 options are mutually exclusive.

https://doc.traefik.io/traefik/providers/file/#directory

To keep the repository focused, we ask that all questions be asked in the [community forum](https://community.traefik.io/). It is pretty active, so you might find that your question has already been answered there. If not, you can ask and get help from other community members pretty quickly.
