### ISSUE TITLE
Support different TLS options for different ClientIP in the same Host

### ISSUE THREAD

**Issue by prokher** [traefik/traefik#10530]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Usage scenario is quite straightforward. Traefik as a reverse proxy manages traffic to HTTP services from both: external network (Internet) and from the local network. The goal is to make it require client TLS certificate from internet clients and do not require such certificates from local clients. In other words, since you are in the local network and have physical access to the network — you are more or less trusted, once you connect from the external network — we require your web browser to have the client certificate installed. The most important particular case is to avoid setting up client certificates on the internal client services, such as CI/CD systems.

Currently, an attempt to configure Traefik in such a way ends with the following error message:
```
found different TLS options for routers on the same host example.example.com, so using the default TLS options instead
```

The particular request is to allow routers with the same `Host` rule and different `ClientIP` rules to have different `tls.options`.

Actually, this issues is a clone of #9426, where @rtribotte [wrote](https://github.com/traefik/traefik/issues/9426#issuecomment-1946242876):
> ... Please, feel free to ask for reopening this issue or open a new one. ...

Since I cannot reopen the original, I am opening a new one.

**Comment by f0sh** [comment]
Hey,

I was about to open another issue relating to #9426, however with a slightly different use case. I wil skip opening, to avoid to many issues on actually the main subject.

## What did you expect to see?

We are running some applications behind Traefik for general public use. However these apps come often with an admin interface under e.g. `/admin` which we like to authenticate against using ClientCerts (no restrictions on the ClientIP though). For nginx and apache you can define directories with (e.g. `Location` tag) special options to use BasicAuth or even ClientCertAuth to access these defined paths.
Traefik also allows to use a middleware to add BasicAuth to certain Paths. However if you want to use ClientCertAuth, Traefik follows a very different approach by using the `tls.options` instead of the middleware. IMHO this is not consistent.

## Suggestions

I would like to suggest to change the implementation if possible to a similar, more unified approach using a middleware to handle the authentication using ClientCerts. I think this way my use case, and the use case of @prokher, @rtribotte and others from #9426 would be solved as well, because using the middleware you have more flexibility and new HostRule can easily be added using another middleware without any interference.

**Comment by jspdown** [comment]
Hey @prokher,

Thanks for reopening the issue.

We are interested in this issue but are unsure about the use case and the traction it will receive, so we are going to leave the status as "kind/proposal" to give the community time to let us know that they would like this.
We will reevaluate as people respond.

**Comment by prokher** [comment]
@f0sh, I love your suggestion of making TLS configuration implemented as middleware. Indeed, it looks more consistent than the `tls.options`-base approach. Honestly, I expected to have TLS configuration somewhere in the TCP middlewares list, and it took a while to realize that it is implemented differently.

Anyway, I believe, it is up to maintainers to decide how exactly this should be addressed. I can only vote for @f0sh's scenario as well. Protecting selected paths (e.g., `/admin`) with client certificates is also the case for us.

@jspdown, thank you. I hope this request will find its way to release eventually. Speaking of a workaround, I still haven't found one. It looks like I can spawn two Traefik instances: the first will manage the IP addresses of the internal network (`ClientIP`), and redirects to the second when a request comes from the internet. The second one will require a client certificate. It seems like a viable workaround, but the appearance of an extra hop does not allow us to call this workaround an elegant one.

😬

**Comment by nmengin** [comment]
Hello @prokher,
This proposal has almost no traction.

We won't add it to the Roadmap yet and we prefer to close it.
We'll re-open it later if necessary.

**Comment by mefernandez** [comment]
Hi, 

I am also looking for a solution. It's quite common for customers to ask me for a mixed login approach in web apps, say user/pass and client certificate. It would be very convenient if Traefik handled both seamlessly.

The workaround is to have a different entrypoint but that needs an extra non-standard https port like 8443.
It would be very nice to handle all requests only via 443 port.

Cheers!

Mariano.
