### ISSUE TITLE
Troubleshooting 502 Bad Gateway: Keep-Alive and Timeout Settings in Traefik

### ISSUE THREAD

**Issue by changhyuni** [traefik/traefik#10932]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've encountered a 502 Bad Gateway error occasionally, and disabling the keepalive option in Traefik seems to have resolved the issue.

From my understanding, the Traefik process flow and timeout settings (keepalive/idle) for each component are as follows:
`Incoming request -> Entrypoint (RespondingTimeouts) -> Router (forwardingTimeouts / maxIdleConnsPerHost) -> Service`

If I disable the keep-alive by setting “maxIdleConnsPerHost = -1”, does it also disable the forwardingTimeouts option? Could you clarify the request flow in Traefik and the timeout configuration for each component?

### What did you see instead?

I tried --serversTransport.maxIdleConnsPerHost=-1

### What version of Traefik are you using?

traefik 2.11.0

### What is your environment & configuration?

```yaml
      - --serversTransport.maxIdleConnsPerHost=-1
```

**Comment by kevinpollet** [comment]
Hello @changhyuni and thanks for your interest in Traefik,

> If I disable the keep-alive by setting “maxIdleConnsPerHost = -1”, does it also disable the forwardingTimeouts option? Could you clarify the request flow in Traefik and the timeout configuration for each component?

The request flow is the right one, setting `maxIdleConnsPerHost=-1` does not disable the fowarding timeouts.

**Comment by changhyuni** [comment]
@kevinpollet 
Hi thanks for your comment.
The configuration setting "maxIdleConnsPerHost=-1", where exactly does this apply in the timeout settings for keep-alive connections? Can I understand it with the following structure? Here’s an example
```
Incoming request(maybe AWS ALB) -> Entrypoint (RespondingTimeouts) -> (maxIdleConnsPerHost) Router (forwardingTimeouts) -> Service

I am trying to understand the effects of different configuration settings:
- The "maxIdleConnsPerHost=-1" setting is applied to the "Traefik entrypoint" and "router" intervals.
- "ForwardingTimeouts" applies to 'router' and 'service' sections.
```

**Comment by juliens** [comment]
Hello @changhyuni ,

From my experience, setting maxIdleConnPerHost to -1 to disable keep-alive is not the optimal solution for addressing the 502 errors you're encountering in Traefik. In my opinion, the issue you're facing is likely not related to the keep-alive connections but rather to the server list refresh process within Traefik.

By configuring maxIdleConnPerHost to -1, you may have seen some improvement, but this is primarily because it reduces performance, which in turn reduces the load and the number of errors. However, this doesn't address the root cause and only mitigates the issue by lowering the error rate.

For me, the real solution is to use the retry middleware, which allows Traefik to attempt another server if the current one is down or unreachable. This ensures better handling of transient failures and improves the overall reliability of your service.

Here's how you can configure the retry middleware:

```yaml
http:
  middlewares:
    retry:
      retry:
        attempts: 3

  routers:
    my-router:
      rule: "Host(`example.com`)"
      service: my-service
      middlewares:
        - retry

  services:
    my-service:
      loadBalancer:
        servers:
          - url: "http://server1"
          - url: "http://server2"
          - url: "http://server3"
```

This configuration will retry up to three times before failing, which can significantly reduce the incidence of 502 errors due to server list refresh issues.

I hope this helps! If you have any further questions or need more detailed guidance, please feel free to ask.

**Comment by changhyuni** [comment]
Hi @juliens.
Thanks you for comment.
```
ALB -> Traefik(forwardingTimeouts.idleConnTimeout(keep-alive) 10 Second -> App(Pod) 20 Second
```
I've conducted various experiments, and one issue I encountered is related to the `--serversTransport.forwardingTimeouts.idleConnTimeout` setting. When this keep-alive timeout is set to a duration shorter than the `application`s without setting `maxIdleConnPerHost` to `-1`, and while keep-alive is enabled, I frequently catch a 502 Bad Gateway error.

In other words, if both the proxy and the upstream service set the same idle timeout durations, or if the upstream service terminates the connection earlier than the proxy, clients are likely to experience HTTP 502 errors.

Anyway, I don't know that the server list refresh process within Traefik.
Can I get some documentation or clarification on this?

**Comment by juliens** [comment]
Hi @changhyuni,

502 errors happen when Traefik has trouble communicating with the upstream server. This could be due to timeouts when sending requests or receiving responses, connection issues, etc.

When Traefik processes events from your orchestrator, it needs some time to apply the new configuration. During this period, it might generate 502 errors because it could still be trying to connect to an incorrect IP. This is where retries can help improve the situation.

We try to keep GitHub issues focused on bugs and enhancements. Could you please continue this discussion on our forum at https://community.traefik.io/?

Thanks a lot!
