### ISSUE TITLE
specify host for service healthcheck

### ISSUE THREAD

**Issue by theblop** [traefik/traefik#10957]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Is it possible to add a `host` parameter to the service healthcheck configuration so that healthchecks could be done against any url and not just the proxied service? There is already a `hostname` parameter for http healthchecks but it's just for defining a Host header in the request.

**Use case:** I have a few services in docker-compose behind traefik that all depend on the availability of a single backend distributed database (part of the compose stack as well). This database exposes an http health endpoint. I'd like traefik to check against this url endpoint for all the services so that they are not exposed if the underlying DB is not healthy. Right now the only way to do that would be to implement and expose that check inside each container.

**Comment by mmatur** [comment]
Hello @theblop,

Thank you for your suggestion. I understand your use case and the need to ensure your services are only exposed when the underlying database is healthy. However, adding a host parameter to the service healthcheck configuration to perform health checks against an unrelated URL might not be the best approach.

### **Reasons**:
- **Service Responsibility**: Each service should be responsible for reporting its own health status. This means that your services should include logic to determine their health, including the status of any critical dependencies like your distributed database.

- **Separation of Concerns**: It is generally not a good practice to define a health check for one service based on the status of another. This breaks the encapsulation principle and makes the health check mechanism less clear and maintainable. Each service should be self-sufficient and encapsulate its health checking logic.

- **Maintainability and Scalability**: By embedding the database health check logic within each service, you ensure that your health checks remain meaningful and maintainable. It also makes it easier to scale and manage the health checks as your system grows.

### **Suggested Approach**:
Instead of relying on Traefik to perform health checks against the database directly, you should update your services to perform this check internally and expose the result as part of their health endpoint. This way, Traefik will only need to check the service's own health endpoint, which will already consider the database's health status.

Here’s a brief outline on how you could implement this:

- **Service Health Endpoint**: Implement a health endpoint in each of your services that checks the status of the database.
- **Internal Checks**: Each service queries the database health endpoint and incorporates this status into its own health check logic.
- **Expose Health**: Traefik continues to perform health checks against the services’ health endpoints, which now reflect both the service’s and the database’s health.

This approach aligns with best practices and ensures that your system is more resilient and easier to manage.

I am closing this issue accordingly.
