### ISSUE TITLE
Http protocol version trim

### ISSUE THREAD

**Issue by dima-bzz** [traefik/traefik#11201]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

When sending a request with a space before the protocol version, 400 Bad Request is returned. If you send the same request to nginx, then everything is fine. At the same time, there are no errors in the logs.

This fine
```bash
printf "HEAD / HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n" | nc 127.0.0.1 80
```

This return 400
```bash
printf "HEAD /  HTTP/1.1\r\nHost: 127.0.0.1\r\n\r\n" | nc 127.0.0.1 80
```

### What did you see instead?

Traffic should allow such a request and not return a 400 error

### What version of Traefik are you using?

3.1.6

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by rtribotte** [comment]
Hello @dima-bzz,

Thanks for your interest in Traefik!

This behavior is due to the Golang net/http server implementation on which Traefik relies.
If you think this should be supported, I recommend opening an issue on their side.

In any case, we are declining this issue as the behavior doesn't look broken, as the RFC states that only one space should separate the `method` and the `request_target` in the request line: https://httpwg.org/specs/rfc9112.html#request.line
