### ISSUE TITLE
Using encodeQuerySemicolons with providers.docker

### ISSUE THREAD

**Issue by brigidspeed23** [traefik/traefik#11208]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?
Similar to https://github.com/traefik/traefik/issues/9164 we've encounter an issue where semicolons aren't being encoded correctly. We'd like to use the encodeQuerySemicolons parameter, however because we are utilising providers.docker and not statically defining entryPoints this doesn't seem possible.

Is it possible to add an option to use encodeQuerySemicolons in conjunction with providers.docker?

### What did you expect to see?

```
traefik:2.7.1
Request: timesheets/export?date=2024-10-07&pay_group_id=99999&location=some%20value%20here
GET /timesheets/export_summary?date=2024-10-07&amp;location=some+value+here&amp;pay_group_id=99999&_=1729555534716
```

###  What did you see instead?
```
traefik:3.2
Request: timesheets/export?date=2024-10-07&pay_group_id=99999&location=some%20value%20here
GET /timesheets/export_summary?date=2024-10-07&amp&location=some+value+here&amp&pay_group_id=99999&_=1729555432411
```

### What version of Traefik are you using?
Issue starts with version 2.7.2, confirmed also occurring with latest.

```
Version:      3.2.0-rc2
Codename:     munster
Go version:   go1.23.2
Built:        2024-10-09T15:18:44Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

Running traefik with command as follows:
```
docker run \
  --name traefik \
  --detach \
  --restart unless-stopped \
  --publish 80:80 \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --log-opt max-size="10m" \
  --publish "8080:8080" \
  --network=payaus_dev \
  traefik:3.2 --providers.docker --log.level="WARN" --accesslog --accesslog.format="json" --ping
```

### If applicable, please paste the log output in DEBUG level
No response

Edit: fix formatting.

**Comment by kevinpollet** [comment]
Hello @brigidspeed23 and thanks for raising this issue,

To be able to use the [`encodeQuerySemicolons`](https://doc.traefik.io/traefik/routing/entrypoints/#encodequerysemicolons) option, you have to define the entrypoint configuration and not rely on the default entrypoint.

Something like the following:

```
docker run \
  --name traefik \
  --detach \
  --restart unless-stopped \
  --publish 80:80 \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  --log-opt max-size="10m" \
  --publish "8080:8080" \
  --network=payaus_dev \
  traefik:3.2 --entrypoints.web.address=:80 --entrypoints.web.http.encodequerysemicolons=true --providers.docker --log.level="WARN" --accesslog --accesslog.format="json" --ping
```

Please note that the entrypoint is named `web`.

It seems that your issue is related to a configuration issue and the GitHub issue tracker is dedicated to bug and feature requests.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v3 section](https://community.traefik.io/c/traefik/traefik-v3). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.
