### ISSUE TITLE
Fragment (#) prefix in the Ingress Rules

### ISSUE THREAD

**Issue by pats4all** [traefik/traefik#11283]
### Welcome!

- [x] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [x] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Hi,
I have a URL that has '#" in the path (https://localhost:8000/#/foo). When I keep the PathPrefix as '/#/foo', that does not passthrough (404). 
As per the URI spec, '#' is a fragment,

`URI = scheme ":" ["//" authority] path ["?" query] ["#" fragment]
`
Wondering if it is a good idea to include the fragment match as part of rule. I know there is a Query match and it would be easy to implement in the same lines for Fragment as well.

// Sree

**Comment by rtribotte** [comment]
Hello @pats4all,

Thanks for your interest in Traefik!

Your are experiencing the expected behavior.

Fragment identifiers are not sent to the server. The hash fragment is only used by the browser.
As mention in [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.5) :
> Fragment identifiers have a special role in information retrieval
   systems as the primary form of client-side indirect referencing

We are closing this issue accordingly.
