### ISSUE TITLE
support log rotation within traefik binary

### ISSUE THREAD

**Issue by daniel-garcia** [traefik/traefik#3489]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Traefik currently supports log rotation by handling SIGUSR1 correctly. This is certainly a very standard way of handling this. However, configuring this in kubernetes is non-trivial. K8s 1.10 landed support for shared [process spaces ](https://kubernetes.io/docs/tasks/configure-pod-container/share-process-namespace/). In order to use this, i would need to create a logging sidecar that handled rotation and configuration of that rotation... also I need to send those logs upstream, etc. Additionally, I deploy traefik with the [helm chart](https://github.com/kubernetes/charts/tree/master/stable/traefik). So now I need to add support to configure arbitrary sidecars, k8s version detection, etc. Life would be easier if I could configure rotation directly as configuration in traefik. This way the side car is just concerned with log shipping instead of also handling rotation.

https://github.com/natefinch/lumberjack
```go
log.SetOutput(&lumberjack.Logger{
    Filename:   "/var/log/myapp/foo.log",
    MaxSize:    500, // megabytes
    MaxBackups: 3,
    MaxAge:     28, //days
    Compress:   true, // disabled by default
})
```

**Comment by daniel-garcia** [comment]
Would the traefik team accept an MR that accomplished this goal?

**Comment by dtomcej** [comment]
I have a few of concerns about this:
- If you are using kubernetes, and are opting to write logs to files, you may want to review your reasoning to do so.

- Logging to stdout is always preferrable, and is supported by a bunch of well-used tools such as fluent, logstash etc.

- When you have multiple replicas, managing log files gets nasty, and the solution is essentially to run one of the previously mentioned tools, which work without log files...

Is there a particular reason that you _want_ log files in a k8s environment?

**Comment by daniel-garcia** [comment]
there are a couple of reasons I want to log to a file vs stdout/stderr. 
* logging to a file I can clearly configure the output type (eg json) and feed that to a structured logger. I can trust that every entry in the log file will be JSON and  nothing else.
* events like panics are completely separated from structured output like JSON
* log files act as a buffer to pushing logs upstream. If upstream log injestion is down, the local log files act at a configurable buffer

I'm not following your statement about "managing log files get nasty". The use of lumberjack makes logfile management very easy. Also, the log files (in my environment) are put into a tmp volume. It doesn't matter how many replicas there are so I don't see how that is relevant. 

The MR to accomplish this would be very small. Exposing the lumberjack parameters in configuration would be all that is necessary along with the initialization of the log output.

**Comment by dtomcej** [comment]
Hey @daniel-garcia,

Here is a bit more clarification on my previous statement:

when I say `When you have multiple replicas, managing log files gets nasty`, if you are using traefik in k8s, and you have 3+ replicas, each has their own log file, that each has to be rotated. What happens if one of the pods doesn't rotate at the right time? what happens if load balancing is uneven, and you have one log file that fills up, and gets rotated 3x faster than any of the other pods? What happens if your pod fails a liveliness check, and the pod gets deleted and recreated, and you haven't triggered a log "push"? These are all things that we have to consider.

When you say `Also, the log files (in my environment) are put into a tmp volume. It doesn't matter how many replicas there are so I don't see how that is relevant` Kubernetes file storage is absolutely something that is of great concern, expecially when adding features. Are you using persistent storage for your log files? If not, your volume could get deleted and erased on pod crash. If you are using persistent storage, then you would have to configure each pod to log using a unique path/filename, since there are multiple pods writing to the same volume. This is where you could run into issues.

I am wary about approving feature addition that may work in one use case, but for the majority are against best practices or design goals.

Just my 2 cents

**Comment by daniel-garcia** [comment]
@dtomcej 

> What happens if one of the pods doesn't rotate at the right time?
With lumberjack, for example, rotation is handled by by the library and is triggered by a set of configured values. The rotation "policy" is defined by the configuration of luberjack. Rotation is not necessarily triggered by at a specific time but by the policy. For example, when the file reaches 100 MB, it is rotated. If it is 28 days old, it is rotated, etc.

> What happens if load balancing is uneven, and you have one log file that fills up, and gets rotated 3x faster than any of the other pods?
The logging behavior of pods are independent from one another. It is the job of the sidecar to take care of shipping logs.

> What happens if your pod fails a liveliness check, and the pod gets deleted and recreated, and you haven't triggered a log "push"? 

Liveness probes are defined as part of the [container lifetime](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/), not the pod lifetime. If a "container" fails a liveness probe, it is restarted. This does not mean the logging sidecar would get restarted. 

> Are you using persistent storage for your log files?
That is not dictated by this feature at all. The logging sidecar could be using a tmpfs volume, a pvc, a host volume, etc and it really is not a concern of traefik how "persistent" or "not persistent" its log file is. Its persistent is dictated by the use case and defined by end users.

I'm quite surprise about your opposition to adding this despite traefik supporting this already via SIGUSR1 see https://github.com/containous/traefik/issues/1696 .  That MR https://github.com/containous/traefik/pull/1761 implements log file rotation by handling SIGUSR1 and having users use a program like logrotate. This could be done in kubernetes today, btw. The current supported file rotation will not work on Windows (that's not necessary for this discussion but worth mentioning). This feature request is about making something that is already possible with traefik (log rotation) easier to do.

Perhaps @emilevauge should weigh in as he approved the first log rotation support.

**Comment by emilevauge** [comment]
Hi @daniel-garcia 
I'm not against adding native log rotate into Traefik. Supporting both "standard" `SIGUSR1` signals and internal implementation seems doable.
I have some concerns with https://github.com/natefinch/lumberjack though, which has been inactive since September 2017, and may have few [bugs](https://github.com/natefinch/lumberjack/issues/56) [waiting](https://github.com/natefinch/lumberjack/pull/57) for some fixes. WDYT ?

**Comment by dtomcej** [comment]
Hey @daniel-garcia 

I would like to start off by apologizing, I re-read my replies from yesterday, and they do come across quite negatively. For that I apologize.

Second, I do actually agree with the feature addition for log rotation and configurability. I think those are features that, to quote a colleague "Are features that should be supported". As @emilevauge noted, we may want to look at different options to achieve this, as potentially that project might not be ideal, but either way, I do agree with the introduction of those features.

Third, you are correct on your lifecycle points. You are obviously familiar and comfortable with k8s, and are obviously capable of handling the "gotchas" of file based logging by shifting the responsibility to your sidecar in your use case. A lot of users may not be as savvy, and we want to be careful promoting features that can be "gotchas" to new users.

For these reasons, I would 👍  the proposal, however decouple your use case (k8s) from the feature request, and would just propose it as a feature for the logging module. That way, _if_ users wanted to implement it in k8s (as you will), and they are willing to address the drawbacks (either via sidecar etc), then they are more than welcome to it.

To quote another colleague:
```
"log everything to stout and have your central log agent aggregate everything" approach comes with its own set of issues that a more decentralized solution may be able to handle better. Thus, I think we should only need to make sure that both models are feasible with Traefik.
```
And I agree with this as well.

For these reasons, I would like to apologize for my negativity so far in this issue, and give the feature request a 👍 from me.

**Comment by daniel-garcia** [comment]
Hi @dtomcej,

Sorry for the delayed response. I've been on holiday. 

I'm fine with not using the luberjack library, @emilevauge . It was just an example. I'll work up a PR in a couple of days as a proof of concept so we can have some code to discuss.

**Comment by dennybaa** [comment]
Hey there @dtomcej!

I'm going to implement the extraVolumes/extraMounts for the traefik helm chart as well as a sidecar which will have sidecar for log rotation. 

My 50 cents for having the rotation built-in are those who use Elastic filebeat, and I do personally use it. _It can only read traefik logs from the file_.
Logging to stdout - yeah awesome sure. But in my case I will have to pass log files between pods via host volume and the rotation could be handy though not required... Sidecar will do the job...

PS. nginx does not have log rotation built-in, however traefik could have :)

**Comment by dennybaa** [comment]
@dtomcej Hi there

> "log everything to stout and have your central log agent aggregate everything" approach
 comes with its own set of issues that a more decentralized solution may be able to handle better.
 Thus, I think we should only need to make sure that both models are feasible with Traefik.

Awesome and we all feel that the above is right and correct. However in the real world scenario tools such as filebeat expect files to read the input from https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-traefik.html#configuring-traefik-module. I'm not expert in different log consumption tooling, though it seems that quite a number of tools expect files :( This is definitely a jet legged.

Recently I've added to traefik k8s chart, `extraVolumes` and `extraVolumeMounts` https://github.com/helm/charts/pull/8723, well now it's possible to share files between pods filebeat and traefik. Well I don't like it too:(

The next step is log rotation it would be no problem to use host's or a side car logrotate to send `USR1` signal to traefik. It would be simple if it was the same PID namespace, but:

- if logrotate was on the host we would need that `docker kill -s` magic with the correct pod container id, consequently **this involves further probably heavy chart mangling**
- if a sidecar container in the same pod - we need to send the signal to another container, with k8s 1.12 it will be easy to support since the pods containers can share the same PID namespaces. **Pretty simple chart modifications**. Though it's a version restriction.
- If traefik supported built-in rotation - it would be the **simplest** chart modification.

The approach taken by me is a [derived traefik container](https://github.com/plasmops/docker-traefik/blob/master/Dockerfile). It's straightforward but it brings external resources (configmap for logrotate config) which is complexity...

**Comment by dennybaa** [comment]
Final thoughts: **I also go for stdout**, it's better use filebeat docker input + ES ingest rather than filebeat traefik module (it doesn't work as expected :)

**Comment by avendretter** [comment]
Hello everyone!
well I have a similar problem. I have linux and windows hosts running traefik. Both should be able to handle rotating logs. Due to the lag of the SIGUSR1 Signal in windows this is not possible at all.

What I would like to see:
A possibility to reload/restart the service e.g. with the service pid, so the logfiles are not locked and can be rotated.
I know that nginx did a similar thing by saving his pid. So a script is able to send the reload command to a running instance of nginx. 
This might also work for traefik?!

Best regards!

**Comment by rcomanne** [comment]
Hello, any updates on this issue?
We have a filebeat sidecar logging architecture and would like to have this feature supported natively.
If I understand correctly, a PR with this functionality would be accepted, but I'd like to know if anyone else did any work or analysis on this issue before.

**Comment by ddtmachado** [comment]
Closing as the [new log library](https://github.com/traefik/traefik/pull/9515) allows users to configure log rotation directly in Traefik
