### ISSUE TITLE
SSL client authentication on per frontend basis

### ISSUE THREAD

**Issue by vladimirtiukhtin** [traefik/traefik#3575]
### Do you want to request a *feature* or report a *bug*?

Feature

### What do you expect to see?

We need to authenticate clients using SSL on per frontend basis. Let's say I have an ingress defined and CA as kubernetes secret. How can I enable SSL authentication on particular path on that ingress? Thanks

**Comment by nmengin** [comment]
Hello @tiukhtinvladimir ,

Many thanks for your interest in the project.

All the TLS configuration is mapped to the entrypoints and not to the frontends but you can make the CA optional in your incoming request as described in the [documentation](https://docs.traefik.io/configuration/entrypoints/#tls-mutual-authentication).

Thus, you can check if the CA is mandatory (or not) directly into your backends.

WDYT?

**Comment by ItalyPaleAle** [comment]
I have the same issue. Would like to enforce client authentication for a single frontend. In my case, the backend application isn't able to validate the client certificate, so making CA optional and passing the certificate to the backend wouldn't help.

In short, I have multiple services behind Traefik: some are public, some are private, and for the private ones I'd like Traefik to request a client certificate and validate the client.

**Comment by tpdownes** [comment]
I agree that this would be helpful for me. Part of the reason is that, even if you make the verification optional, a browser that has certificates in it will prompt you to select one when you first browse to any site on the host.

For others, I think a reasonable approach would be to have an entrypoint on a non-standard port like 8443. It's certainly not ideal -- and might not work given firewall realities -- but client certificates are a funny business to be in anyhow.

**Comment by Yajo** [comment]
This is wrongly labeled as a question. The answer is "you can't", and this is an important topic, so this should be a feature request IMHO.

**Comment by ataraxus** [comment]
Stumbled upon this, right after deploying traefik for all of my containers. This feature would be most appreciated.

**Comment by ABeltramo** [comment]
Is it possible to enforce the TLS by passing `optional=false` but still make it work with LetsEncrypt? 
Example config:
```
[entryPoints]
    [entryPoints.https]
      address = ":443"
      [entryPoints.https.tls]
        [entryPoints.https.tls.ClientCA]
            files = ["<redacted>"]
            optional = false


[acme]
  caServer = "https://acme-v02.api.letsencrypt.org/directory"
  email = "<redacted>"
  storage = "acme.json"
  entryPoint = "https"
  onHostRule = true
  [acme.tlsChallenge]
```
Because in this case the tls challenge from LetsEncrypt will fail because they are not providing the client certificate.

**Comment by Queuecumber** [comment]
News on this? It's a useful feature and nginx ingress can already do it

**Comment by dduportal** [comment]
Hi, for information the version `v2.0` of Traefik will have improvements over this, as the `tlsOptions` have moved in the configuration: https://docs.traefik.io/v2.0/https-tls/overview/ (they are now defined at the [Router](https://docs.traefik.io/v2.0/routing/routers/), which is the renamed - and improved- object that was referred as "frontend" in Traefik `v1.x` as per https://blog.containo.us/back-to-traefik-2-0-2f9aa17be305#3f17).

This new Traefik is currently alpha, so wait and see :)

**Comment by ataraxus** [comment]
Hey folks, so this I haven't a chance yet to try this out, but it seems to be resolved for traefik >v2? I guess this issue could be closed? 
@dduportal if you have a link to a working example for client certs per router (frontend in v1) it would be nice if you would share it.

**Comment by pxeger** [comment]
Any updates, especially now that 2.0 is de facto? The comments above hint that it's possible in 2.0, so could that be clarified?

**Comment by Okeanos** [comment]
I stumbled across this as well in the past few days.

What I need is the following:

The ability to specify mTLS (mutual TLS / client certificate) authentication with distinct CAs for different paths on the same host address. The ability to use `RequireAndVerifyClientCert` in its current form is insufficient because I want the different paths to be treated differently with separate CAs applying to each. "Overlapping" CAs, i.e. I don't know which of them is actually used for verification, are not a solution to my problem. I also cannot implement mTLS in the backend applications (which would render the mTLS option in Traefik obsolete anyway).

Related threads / discussions that I found that also require this or something similar:

- https://community.traefik.io/t/default-tls-options-without-host/13238
- https://community.traefik.io/t/many-found-different-tls-options-for-routers-on-the-same-host-errors/13852
- https://community.traefik.io/t/restrict-http-url-path-using-mtls/10650
- https://community.traefik.io/t/multiple-mtls-options-based-on-path-rules/4602
- #6362

None of these have an actual answer :(
