### ISSUE TITLE
Add a provider for DynamoDB in Traefik v2

### ISSUE THREAD

**Issue by jbdoumenjou** [traefik/traefik#4676]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Traefik v1 supports dynamic config generation for and from a DynamoDB service, i.e. it has a DynamoDB provider.

Now that the main changes for v2 are out, we can re-add previously supported providers, such as the one for DynamoDB.

The existing providers, as well as the code for the DynamoDB provider in v1.7, can be used for inspiration.

**Comment by jmaraujo** [comment]
Hi,

I'd love to test and use it in production... Please consider DynamoDB as provider

**Comment by martin-nikolov** [comment]
Hi,

Any update on that would be highly appreciated!

Thanks!

**Comment by kevinpollet** [comment]
Hello,

After some discussions with the team, we thought that it would be better to support the dynamodb provider as a provider plugin (available since Traefik v2.5).

For more details, check out the documentation available in the provider plugin demo repository: https://github.com/traefik/pluginproviderdemo

According to this, we will close this issue and decline #8542.

Thanks again for your interest in Traefik!
