### ISSUE TITLE
Clarify Rate-Limiting use in Kubernetes

### ISSUE THREAD

**Issue by trondhindenes** [traefik/traefik#4867]
### Do you want to request a *feature* or report a *bug*?
Bug

### Did you try using a 1.7.x configuration for the version 2.0?
- [x] No

### What did you do?
This isn't a bug per se, but it might be a "documentation bug". I'm looking for some clarification around how to use rate-limiters with Traefik on Kubernetes.
Example situation: I have an app that can handle 10 rps per container instance. I need to make sure that each container never gets more than 10 rps. This means that if scaled to 2 pods, the service can handle 20 rps, if scaled to 5 it can handle 50 and so on. 

I'm unsure how (and if!) Traefik supports this type of rate limiting based on scale. We're discussing this internally at the moment and are unsure if we have to implement ratelimiters in the application middleware itself, or if Traefik can handle it for us in such a way that the limiter is "per pod" based and not just a hard limit for the entire service. It would be good if the documentation was a bit clearer on this topic - maybe even a complete section on rate-limiting since there are multiple open issues regarding how to configure it.

**Comment by juliens** [comment]
Hi @trondhindenes , thanks for your interest in Traefik!

For now, rate limit in Traefik is only on the frontend part. It means that you can only do some rate limit between a user and a Traefik frontend. May be we can add something in the documentation to clarify this.

Rate limit "per pod" is not as simple as we can think at first, because, your rate limit should take care of how you loadbalance on servers. So it seems that what you need is more like a "new" loadbalancer type which take care of one server load capability. WDYT?

**Comment by trondhindenes** [comment]
Hi @juliens thanks for commenting.
Yes probably a new loadbalancer type or even a new circuitbreaker type could be the place to implement this.
Since the loadbalancer attribute doesnt support "expressions", maybe a circuitbreaker is a more logical place to do this - something like:
```
[backends]
  [backends.backend1]
    [backends.backend1.circuitbreaker]
    expression = "MaxRps() > 10"
    [backends.backend1.servers.server1]
    url = "http://172.17.0.2:80"
```
I would still prefer this to be a per-server setting than a per-backend setting (similar to "weight") tho. So maybe some completely new construct is needed, something like:

```
[backends]
  [backends.backend1]
    [backends.backend1.circuitbreaker]
    expression = "MaxRps()"
    [backends.backend1.servers.server1]
    url = "http://172.17.0.2:80"
   maxrps = 10
```
That would allow configuring the setting on a per-server level, but actually activate the setting on a per-backend level, which kindof makes sense to me.

**Comment by Xyaren** [comment]
Just encountered this issue as well.
Since this is 3 years old, has anything changed, that would allow for a decent workaround?

**Comment by mmatur** [comment]
Hi,

@trondhindenes I'm closing this PR because it is relative to Traefik v1, since this issue documentation has been revamped. Feel free to reopen this issue if needed.

@Xyaren if you encountered the same issue could you please open a new issue with detail on your use case and the Traefik version you are using

Thanks to both of you
