### ISSUE TITLE
v2: support `NOT` in `rules` definition

### ISSUE THREAD

**Issue by Kosta-Github** [traefik/traefik#5228]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I would like to see support for `NOT` (or `!`) in addition to `AND` and `OR` for defining routing `rules`, just to enable support for proper `boolean` operations.

E.g.:
```text
rule = "Host(`traefik.io`) || (Host(`containo.us`) && NOT Path(`/no-traefik`)"
```
or (note the `!` in front of `Path()`):
```text
rule = "Host(`traefik.io`) || (Host(`containo.us`) && !Path(`/no-traefik`)"
```

**Comment by denysvitali** [comment]
I was about to open an identical issue, but found yours:
here is my original issue:  
   
---
### What did you expect to see?

When writing a router rule, it would be nice to be able to negate parts of the expression, e.g: 
```
[http.routers.https-redirect]
   rule = "HostRegexp(`{any:.*}`) && !Host(`localhost`)"
   middlewares = ["https-redirect"]
   service = "dummy"
```

Currently this feature doesn't seem to be mentioned in the [documentation](https://docs.traefik.io/v2.0/routing/routers/#rule), nor it seems to exists a set of allowed operators (only `&&` and `||` are mentioned in a green "admonition").

---

I think that using the `!` operator will result in a more clean code (and will be more consistent with the `&&` / `||`) operators -- either we go with the Python style operators (`and`, `or`, `not`) or the C style operators as they're being used now (`&&`, `||`)

**Comment by glebovdev** [comment]
NOT (or !) operator support feature is still pretty much needed. 
My use case, for example: show basic auth only for those who do not provide a specific header in request. 
But the following code of course doesn't work as expected:
<pre><code>- "traefik.http.middlewares.auth.basicauth.users=user:hashed_password"
- "traefik.http.routers.traefik-auth.rule=!Headers(`PassBasicAuth`, `true`)"
- "traefik.http.routers.traefik-auth.middlewares=auth"</code></pre>

**Comment by everflux** [comment]
I would like this as well - especially in the context of a TCP router. I would like to express "if no SNI host is present" (plain TLS handshake without SNI).
Use case: forward these connections to a special handler while providing https on the same port for browsers

**Comment by CourtneySherman** [comment]
I will add another plus for this feature request and another use case. For services that allow api calls, the not operator would make it much easier to allow the api calls to bypass middleware based authentication (basic auth, authelia, oauth).

**Comment by michael-robbins** [comment]
What's the current 'workaround' for implementing this logic now?

Just use a regex based approach including a negation?

**Comment by CourtneySherman** [comment]
It can be done with multiple routers and carefully crafted rules statements with the right priorities set. It works, but it's a lot of configuration for a fairly simple logical test.

**Comment by ldez** [comment]
Take a look to https://pilot.traefik.io/plugins/270947803019084288/block-path

**Comment by ssikyou** [comment]
Need it too!

**Comment by k3daevin** [comment]
> Just use a regex based approach including a negation?

That sounds interesting. Can you give an example?

**Comment by oliversalzburg** [comment]
> > Just use a regex based approach including a negation?
> 
> That sounds interesting. Can you give an example?

Here is my solution.
```
Path(`/(?!api/v3){-:.*}`)
```

In the case of `Path`, you need to make sure to start the expression with `/`, `^` is not accepted and the `/` must be part of the path. So start your negated match _after_ the `/`.

Also ensure you have _any_ capture group in the path, otherwise traefik doesn't get that you want regular expressions.
`{-:.*}` is my capture group. It's named `-`, that's why it might look weird. As this is purely to trigger the regex support, I felt it's fine.

**Comment by aragon999** [comment]
I am also very interested in this feature, for now I will work around this problem, by creating some complicated setup.

But I had a quick look at the code, I think for someone who is better in Go than I am (or understands the codebase better) this should be trivially to implement, since the upstream library supports this feature, as far as I understand: 
https://github.com/vulcand/predicate/commit/482b8f2fdcf09dc59955823a7d7bf5dd55d7365a

So the task left would be to write a handler for the "NOT" function:
https://github.com/traefik/traefik/blob/v2.4.8/pkg/rules/parser.go#L113-L114

And probably some other parsing things.
