### ISSUE TITLE
Provide onDemand ACME certificates like traefik 1.7 did

### ISSUE THREAD

**Issue by everflux** [traefik/traefik#5349]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
I want to configure a regexp subdomain and get ACME certificates on demand as single certificates as it was possible with traefik 1.7 in traefik 2.
Additional discussion in https://github.com/containous/traefik/issues/5342

Use case is a static traefik configuration that terminates TLS and forwards requests to f.e. Ingress in external kubernetes cluster. (traefik in front of multiple clusters f.e.)

**Comment by ldez** [comment]
Take a look to https://github.com/containous/traefik/issues/2212#issuecomment-359703331

**Comment by everflux** [comment]
Thanks for the pointer. I understand that the option involves some risks but it seems like there are multiple use cases for this feature and honestly it was _the_ selling point for traefik for me. If it would work in the new design of traefik 2 it would be really good to keep. (It is especially painful to get taken away after being available and working flawlessly)

**Comment by SantoDE** [comment]
Which platform are you running @everflux ? For example on k8s its not much of an issue, as you can declare it on the IngressRoute :) Or what am I overlooking?

**Comment by everflux** [comment]
I am running traefik 2 as border http router using just docker. TLS is terminated and requests are routed to an appropriate kubernetes cluster with traefik 1.7 as ingress implementation (not doing any TLS at the moment)

**Comment by jkarni** [comment]
> Take a look to [#2212 (comment)](https://github.com/traefik/traefik/issues/2212#issuecomment-359703331)

@ldez these seem like reasonable concerns, but also solvable:

1. on demand certificate generation can happen conditionally rather than always, to prevent DoS. People suggested a custom function. Another option, I imagine, is to only allow a limited number of certs with the same [eTLD+1](https://pkg.go.dev/golang.org/x/net/publicsuffix) (I imagine it's not easy to get enough eTLD+1s to do a DoS attack.
2. only do certificate generation if no other certificates matched. This should make requests only slower if they in fact need certificate generation

With this approach, do you imagine a PR would be accepted?

**Comment by nmengin** [comment]
Hello @jkarni,

Thank you for your proposition.

This proposal was opened a long time ago with almost no traction.
We won't add it to the Roadmap yet and we prefer to close it.

We'll re-open it later if necessary.
Thank you @everflux  for the suggestion.

**Comment by everflux** [comment]
Thanks for taking the time to consider it.
