### ISSUE TITLE
[Metrics] Metrics on endpoint performance

### ISSUE THREAD

**Issue by 0xVox** [traefik/traefik#6833]
### Do you want to request a *feature* or report a *bug*?
Feature

### What did you expect to see?

The metrics exporter is good for an overview of request statuses and durations, but it would be really useful to be able to see performance of different endpoints on the same service. 

If we have a service with two endpoints A and B, which have varying response times due to the amount of processing required to answer or process the request, the metric for the duration of the request at the entryPoint / Service (with addEntryPointLabels + addServiceLabels options enabled) becomes an average of the two, but we wouldn't be able to compare the performance of two endpoints within the service. 

The endpoint is visible in the access log, so I (possibly naively) assume it would be possible to have these values added as labels to the metrics. I understand this will in a lot of cases bloat the metrics quite significantly, so having the feature behind a switch like the entrypoint and service labels is probably for the best. 

The ability to filter these down to the service level - i.e. endpoint metrics enabled or disabled by service name and/or endpoint they hit would be a major plus. 

Cheers for all your work guys! Would love to know the feasibility of this, whether you want to implement it, or whether you don't have much time but would be able to point someone in the right direction for getting this done :)

**Comment by 0xVox** [comment]
Cheeky workaround to solve my usecase:

https://github.com/0xVox/traefik-officer

**Comment by rtribotte** [comment]
Hello @0xVox,

By looking at this issue with other maintainers and giving it a second thought, we decided to decline it.
We are especially concerned by the cardinality of a metric that would include the server address to identify the selected server behind the service.
As well, in dynamic contexts, this metric won't be accurate as soon as the IPs are renewed.

While the current stance is to close this issue due to its lack of suitability, we remain open to reconsideration if anyone believes otherwise.
