### ISSUE TITLE
Filtering out ping access logs

### ISSUE THREAD

**Issue by MikaelElkiaer** [traefik/traefik#6861]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?
I would like for the option of filtering out calls to /ping in the access log.
My readiness checks in Kubernetes are called very frequently, so having all these calls to /ping in the access log clutters the view.
A possible solution is adding additional filtering of access logs, for example based on RequestPath (e.g.: /ping), RouterName (e.g.: ping@internal), or RequestPort (e.g.: 8080).

I cannot find any issue mentioning this, and only a dead community post: https://community.containo.us/t/is-there-a-way-to-filter-out-ping-requests-in-access-logs-output/4356

**Comment by notsureifkevin** [comment]
Hi Mikael, thank you for the feature request.

One possible solution to this would be to add a regex filter to the `access.log` configuration provider.

(idea stolen from https://docs.nginx.com/nginx/admin-guide/monitoring/logging/#enabling-conditional-logging)

**Comment by MikaelElkiaer** [comment]
> Hi Mikael, thank you for the feature request.
> 
> One possible solution to this would be to add a regex filter to the `accesslog` configuration provider.
> 
> (inspired by: https://docs.nginx.com/nginx/admin-guide/monitoring/logging/#enabling-conditional-logging)

That would do the trick. :)

**Comment by BulatSaif** [comment]
I have the same problem but with prometheus /metrics endpoint, will be nice to filter it out.

**Comment by yongzhang** [comment]
the same request

**Comment by dhirschfeld** [comment]
This would be a very valuable feature. On top of hiding useful information in a flood of irrelevant logs it also dramatically increases the *cost* of monitoring `traefik`. On my AKS cluster, monitoring the `traefik` logs with Azure Monitor is by far my biggest monitoring cost to the point where I will probably have to turn off access logs entirely.

![image](https://user-images.githubusercontent.com/881019/107311678-7e575700-6ada-11eb-9747-5fbb1035ffa7.png)

**Comment by dhirschfeld** [comment]
***xref:*** #6059

**Comment by fredsig** [comment]
I use Traefik behind an AWS ALB. The ALB is configured to hit Traefik's /ping endpoint every 15 seconds. Since I always have at least 3 different ip's, this can fill my logs quickly. Would love to filter this somehow. I've managed to use `--accesslog.filters.minduration` as these requests take usually less than 1 ms but this also means that all internally produced codes (without any route request) will also not show, like 429 http codes on requests triggered by rate limiting. Ideally, a filter on /ping path or even the router name ping@internal would be great. Thanks.

**Comment by Heisenberg74** [comment]
Hi, I have the same problem and same request.

I would like this option, could be configurable per service with annotation ?

Thanks for your support

**Comment by rwjack** [comment]
Hey, I recently encountered the following issue.

It seems websockets can only use GET requests, meaning every time the bitwarden extension in my browser calls the websocket URL that's proxied by traefik, it also sends an access token in the GET request, which effectively saves the token in traefik's log files. I thought it would be a great idea to use some sort of log filtering mechanism by traefik, to ignore specific routers, or to ignore logs based on some other type of filtering.

[Issue for reference](https://github.com/bitwarden/clients/issues/4290)

**Comment by rtribotte** [comment]
Hello,

We want to address this (as well as #9170, including also the metrics) for the next major version (v3).
So far we are planning to remove the access logging for internal services completely.

**Comment by helmut72** [comment]
@rtribotte

> So far we are planning to remove the access logging for internal services completely.

Found this issue because my evaluation of Traefik is flooded with `/metrics`. Is this feature still planned? 

Should be extended to individual log configuration per virtual hosts/services for chatty apps or apps, where 4xx or no log are enough. An argument ["We recommend that you leave the task of processing logs to a dedicated log manager software"](https://github.com/traefik/traefik/issues/6369) doesn't sound plausible, because `/ping` or `/metrics` can be also processed on a dedicated log manager ;)

**Comment by rtribotte** [comment]
I'm closing this issue because PR #9633 has been merged and seems to address this issue.
Don't hesitate to ask for reopening if you think this is not the case.
