### ISSUE TITLE
[doc] bring back the "easy" kubernetes deployment

### ISSUE THREAD

**Issue by kallisti5** [traefik/traefik#7029]
In Traefik 1.7, there was a simple "fast path" to deploying traefik in a kubernetes deployment:

* https://docs.traefik.io/v1.7/user-guide/kubernetes/

The documentation gave a few yaml's to rapidly get Traefik running on vanilla k8s (with some slight tweaking)

The current guide:  https://docs.traefik.io/user-guides/crd-acme offers no such steps.

It's focused on k3s now, which isn't used by as many folks vs the vanilla steps which apply everywhere reguardless of deployment strategy.  It also forces the crd method, vs sticking to the simpler (easier to understand for a quick deployment) IngressRoute + label method.

Traefik v1.7 was such a good release, please go back to your roots somewhat and get away from the obfuscation. I can't push Traefik as a solution anymore since everyone I speak to hates the CRD model and can't follow the jumbled documentation.

**Comment by kallisti5** [comment]
As a side note, the helm charts the v2.2 documentation mentions don't even work with 2.x, so what *is* the actual setup/installation path?

**Comment by ldez** [comment]
https://docs.traefik.io/v2.2/getting-started/install-traefik/#use-the-helm-chart

**Comment by kallisti5** [comment]
ok, so 2.x is in the containous repo.  Is that a CRD deployment or a IngressController + Label deployment?  Flipping through the char it appears to just be CRD.

**Comment by AndrewSav** [comment]
> Is that a CRD deployment or a IngressController + Label deployment? 

How would they be different?

**Comment by gamunu** [comment]
I just started looking into installation documentation, it will get so confusing if you are not using helm. Please bring back the pure k8s YAML based installation instructions.

**Comment by kallisti5** [comment]
> I just started looking into installation documentation, it will get so confusing if you are not using helm. Please bring back the pure k8s YAML based installation instructions.

100% correct.  I'm personally not a fan of stacking layers on layers for critical infrastructure.  I really want to know how stuff works and don't want to "blindly depend" on someone's templates.  That's a formula for stuff breaking and not being able to fix it.

**Comment by notsureifkevin** [comment]
> 
> 
> > I just started looking into installation documentation, it will get so confusing if you are not using helm. Please bring back the pure k8s YAML based installation instructions.
> 
> 100% correct. I'm personally not a fan of stacking layers on layers for critical infrastructure. I really want to know how stuff works and don't want to "blindly depend" on someone's templates. That's a formula for stuff breaking and not being able to fix it.

Networking in Kubernetes is far from trivial, and with the added support of Traefik v2 with middlewares, advanced routing, TCP/UDP support, and more provides a lot of flexibility for users. What this meant was until Kubernetes caught up with some of these concepts (now available in 1.18), the complexity fell on the community to provide solutions for advanced use cases.

The ecosystem has moved very fast, and this ultimately meant CRDs, RBACs, and the neccessity to support annotation based installs as well. Now, we're supporting the most recent [Ingress API improvements](https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/) made in 1.18 which just means more options for you, the end user.

We're really trying our best to keep up with this fast moving train, but in order to do so we have to rely on the community, the tools out there (like Helm), to help keep the installation, maintenance, and support moving forward. In addition, we'll be working on supporting the upcoming [service-apis](https://github.com/kubernetes-sigs/service-apis) -- what we need from our community is help improving the documentation, providing use case examples, giving us actionable feedback on how to improve the documentation.

Now, I appreciate you would like us the "fast path" to installing Traefik on Kubernetes, but I'd ask what actions can we take to do this? How can we make it easier to install Traefik on Kubernetes, while supporting all the features of Traefik v2, and the features that Kubernetes itself continues to release? If you have some concrete ideas on how we can achieve this, please open a PR, otherwise, I'm going to suggest closing this issue since there is no related PR or proposal here to speak of.

**Comment by kallisti5** [comment]
> Now, I appreciate you would like the "fast path" to installing Traefik on Kubernetes, but I'd ask what actions can we take to do this? 

This is easy, and several folks now in this thread have stated it.  Just offer the "baseline" deploying Traefik to a kubernetes cluster like you used to offer in 1.x.  There were two YAML's for RBAC and the Traefik deployment.

aka:
https://docs.traefik.io/v1.7/user-guide/kubernetes/

It was simple, concise, and gave folks a good view on how things work.  I think Traefik has gotten *DEEP* down in the weeds on the most complex use cases, and completely ignored the core reason people use it... reverse proxy / ingress controller / ACME to containers with vhost support.

I've tried to swing Traefik 2.x to several groups professionally now... and always gotten the same feedback "oh, way to complicated. We'll just use an nginx reverse proxy"   I never had that issue until 2.x came out.

The workflow for 1.7 with ingresscontroller + labels was basic + understandable.  That workflow has completely dried up in 2.x without a replacement.

**Comment by AndrewSav** [comment]
I feel that until https://github.com/containous/traefik/issues/5473 is done, documenting the current CRDs separately may be a wasted effort, as CRD are going to change significantly anyway. I personally reference the current CRDs from [here](https://docs.traefik.io/user-guides/crd-acme/).

**Comment by kallisti5** [comment]
@AndrewSav Look at the big brain on Voyager:
  * https://voyagermesh.com/docs/v12.0.0/setup/install/

Documenting how to generate yaml from helm without needing to use helm within your cluster.

**Comment by AndrewSav** [comment]
@kallisti5 You can find [helm tempalte](https://helm.sh/docs/helm/helm_template/) documentation here, which tells how to render a helm chart into a yaml manifest, that can then be applied to you cluster with `kubectl apply` or `kubectl create`. I'm not sure though what is the relevance of that to this issue, you might need to spell it out for me.

**Comment by kallisti5** [comment]
The fact that y'all don't get what myself and other users are asking for shows that the target audience for Traefik has shifted a lot since v1.7.

I really don't think there's much interest in implementing these improvements or accepting PRs making improvements. Given that I'm going ahead and closing this one.

**Comment by notsureifkevin** [comment]
@kallisti5 on the contrary, we're very interested in accepting improvements to the documentation. unfortunately, we've just not had anyone from the community contribute a PR on this issue, and the team is focusing on improving the support for Kubernetes with the new [Service APIs](https://github.com/kubernetes-sigs/service-apis) that will be released very soon.
