### ISSUE TITLE
Support for private plugins

### ISSUE THREAD

**Issue by negasus** [traefik/traefik#7088]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

Support for private plugins. Connecting plugins from private repositories.

Maybe: this plugin must be placed locally, and we should to define path to plugin in the configuration file. 

That plugin should not be traking by Pilot

**Comment by emilevauge** [comment]
Hi @negasus 👋 
Plugins are super fresh in Traefik, and for now, we want to focus on making those stable. 
Even though there are specific use cases where you need private plugins, right now, we do want to focus on the most requested feature: open source plugins.
But we would love to hear some use cases where private plugins would be required.
Thanks :)

**Comment by negasus** [comment]
I'm not suggesting doing this right now)

For example:
In my case, we need to authorize users by the auth header. And I want to make plugin for obtain some data from Database, cache it, and use this data fot check users. This case very specific for out application. And may contains some business logic.

**Comment by koalado** [comment]
Would love to see support for plugins in private repositories as well.
Following...

**Comment by lexfrei** [comment]
> But we would love to hear some use cases where private plugins would be required.

@emilevauge, in some cases, I have to use traefik in intranet, so there is no option to use pilot or else, but I can place plagins in private repos in local git or place them directly to the docker-image.

**Comment by dio-trinny** [comment]
I would also love this. there's some logic that we need to run specific to us, and I'd rather not expose the logic or create a non-reusable plugin

**Comment by xavivars** [comment]
The other part of the current plugin implementation is that it requires the routing to be connected to Traefik pilot. 

I don't have any problem open-sourcing the plugins I need, but I'd love to be able to create plugins that, for example, enable more middlewares, but being able to do that without having to connect to an arbitrary server at runtime (or startup time) to download arbitrary code (even if signed by Traefik). Instead, I'd like to build "my own" Traefik version, with any plugins I need built into the image.

Other reverse proxies like Skipper allow any developer to do that easily, and I would hope to be able to do the same with Traefik.

**Comment by xavivars** [comment]
@SantoDE : you mentioned in #7515 that private plugins goes against the spirit of the "open-source" catalog

(quoting)

> The challenge I see with private plugins is that it directly contradicts many of the positive outcomes we're trying to achieve with the plugin feature.

and also asked to continue the conversation here. 

Could we continue the conversation here? 

My use case is: I have a very specific rule I want to introduce, where using native traefik rules would be extremely complex. But could be extremely simple if I could add a new rule type (similar to what I can do with (custom predicates in Skipper)[https://opensource.zalando.com/skipper/tutorials/development/#predicates]

I want to forward to one backend or the other based on a relatively complex condition

```
- Path(/foo) && MyCustomRule(true) -> backend1.example.com
- Path(/foo) && MyCustomRule(false) -> backend1.example.com
```

`MyCustomPredicate(input)` would be something like

```
complexRule := Query(`foo=bar`) && !Query(`other=value`)
return complexRule == input
```

How am I supposed to solve this problem using native rules, or current plugin architecture?

**Comment by jorge07** [comment]
I would like to use plugins but due to legal requirements I can't use Pilot or allow any remote code download.
Reading the linked issue, there're reason I don't really understand.
- Why the ability to write, store and run my own plugins makes traefik less open source and force me to use a private service like Traefik Pilot doesn't?
- Using Kubernetes ecosystem as example, in many scenarios you need signed images to be able to run it into your platform, or at least have the opportunity to. Enable something like Traefik Pilot it's a back door that can't be accepted under certain scenarios (that for the work I use to do are the most)

**Comment by lion7** [comment]
Exactly the same issue here. I'm not allowed to connect our internal Traefik proxy to an external service due to security constraints, as that creates a potential attack vector. 

It makes me kind of sad that a request such as this (and also the PR mentioned ealier) isn't taken more seriously. 

I also don't see what "open-source" has to do with preventing plugins from being used offline...
Actually I just wrote an open-source plugin specifically for a use case at my current job (https://github.com/lion7/traefik-jwt-headers-plugin). It works great on my laptop, but now I can't use it on our server due to the ealier mentioned constraints.

For me, a private repo isn't really necessary but the ability to use plugins offline is very relevant.

**Comment by md2k** [comment]
almost a year and no decision on that, while i can see some ideas already implemented for EE version. Seems it is time to start looking for alternative or compile each time won binaries. what is strange because Traefik is MIT and Yaegi under Apache 2, why not just remove Pilot lock and let people use plugins locally. 
As other guys from above we can't connect our instances to 3rd party services due to security concerns. EE version is an option, but i not see any confirmation that EE free of such limits also if i can't prove that Traefik plugins so nice it is "no go" to ask for EE budget.

**Comment by pagran** [comment]
In my case [automatic fork](https://github.com/PrivPlugMatt/traefik-private-plugins) is acceptable, maybe someone will help too.

**Comment by SantoDE** [comment]
Hey all :wave:,

Im sorry for the long time without another response from our side on that quite important topic here.
 
Be assured, it's certainly not about "letting things rot" but rather, try to come up with a solution :)
First of all, our goal has always been to commit to the Open Source philosophy and thus, Traefik plugins should be open sourced as well.

However, we do understand that this topic is a pain point for you since it forces Traefik to be able
to potentially speak "outside" the cluster and at the same time, have a hard dependency on our systems (Pilot).

For the EE version, we were able to solve that issue a couple months ago by deploying a local plugin registry alongside our Traefik EE control plane, which handles most of the job Pilot does for Traefik.

However, this solution is not applicable for Traefik in itself for obvious reasons, as the EE version 
follows a completely different architecture and is not just "a good old proxy". 

That being said, we are actively (as of this week) discussing alternatives how we can allow the usage of private plugins locally, while still trying to solve our goal of having plugins open sources.

I'll let you know soon, once I know more.

**Comment by lion7** [comment]
Can't you just force the regular Traefik proxy to only work with open-source plugins residing on GitHub.com? 
Or making Yaegi only compile open-source plugins? I geuss there are a dozen possibilities that would prevent people from seeking alternatives or forking this awesome project. I'd rather grab my updates from the main repo instead of some fork.

From the point of view of my current job the problem is not really using source code from the internet, because choosing which plugins to use is a decision that developers can make for themselves. But, that plugin should be able to do its work without allowing a remote party to 'peek' inside the infrastructure. Once downloaded, I should be able to block all outgoing traffic and it should still just work.

Obviously, a plugin author could add malicious code to an used plugin. But that scenario can be easily dealt with by implementing proper policies about when and how to update plugins, etc. I just don't really see a strong (technical) argument why a connection with Pilot is absolutely necessary for plugins to work, they're just made of code like all the other built-in middleware...

**Comment by xavivars** [comment]
Hey, Manuel, thanks for replying.

If there's something as simple as https://github.com/PrivPlugMatt/traefik-private-plugins that can be done, there should be plenty of ways to natively solve this issue. 

To me, the effort you're putting towards force everyone to only be able to use open-source plug-ins doesn't align with MIT licenses, where everyone is able to do whatever they want with the code. Or GPL, which enforces its open-source vitality much more than MIT, doesn't go that far: you're only forced to redistribute the code if/when you also redistribute the binaries. And not even AGPL, which forces you to give the the code to the anyone who "uses" the software. But every single open source license gives you the freedom to use the code privately however you want. 

So I think you should reconsidered relicense Traefik to a different license that better fits the spirit of what you want to achieve, to avoid any misunderstanding. But MIT is definitely not aligned with what you're trying to do.

**Comment by md2k** [comment]
Thank you, @xavivars,  for sharing your patch, it will save my time!

**Comment by SantoDE** [comment]
Hey everyone :wave:

Sorry for not coming back to you last week, but we had some things to clarify first :)

After further consideration and assessment of the situation, we want to bring
private plugin support to Traefik.

As I already described last time, we totally can see the need to be somewhat independent
on our systems for using plugins, and thus, we want to improve this situation for everyone in the community. Doing so for Traefik EE was relatively easy, but we weren't so sure about how its do-able for Traefik Proxy easily.

To do so finally, we can imagine two different approaches:
* deploy an own local registry (as we do on Traefik EE)
** advantages: we can still ensure integrity & versioning of plugins, potentially
support different locations where to store plugins
** disadvantage: a bit more complex to setup
* just load plugins from a volume (as it was already proposed in 2 PRs)
** advantage: simple to first use
** disadvantage: you have to handle integrity, versioning etc

Let's discuss together in this issue, and see which option makes the most sense. Ideally, we would
love to include that possibility with the next upcoming release of Traefik V2.5 :)

**Comment by md2k** [comment]
@SantoDE  as for me i see benefits from both solutions registry and/or local. 
Because for example some people who not have strong restrictions still can benefit from using pilot plus as extra they will have opportunity to use local-folder plugins or/and extra private/public registry.
So i can see functionality where you can allow to use: 
1. Pilot public registry 
2. Custom private registry
3. Local location (folder) plugins
And it will be nice to use one of the ways or as combination. Also i think Traefik EE will benefit from this as well, because i can see that as EE user i would like to have ability also use private registries but maybe local-folder based plugins.

**Comment by xavivars** [comment]
I also agree that local plug-ins is probably the easiest option, and by being able to pass a custom path (or have a default one that can be mounted using a volume or a Dockerfile that builds on top of traefik one) should be enough.

And as md2k says, you could leave private registries for the EE version

**Comment by md2k** [comment]
@SantoDE do you ave some good news for us ?

**Comment by SantoDE** [comment]
We are working on it @md2k :)

**Comment by justuspfaue** [comment]
> We are working on it @md2k :)

May I ask when we can expect this feature to hit the public? The issues under v2 doesn’t seem to include actions. Thanks for your work!
