### ISSUE TITLE
Add EAB support for ACME client

### ISSUE THREAD

**Issue by mikesir87** [traefik/traefik#7118]
## Background

Many universities leverage InCommon for their TLS certs, who has support for the ACME protocol. However, they require usage of the EAB (ExternalAccountBinding) mechanism. As an example using certbot:

```
certbot -d <domain.com> --server <ACME_Server_URL> --eab-kid <EAB_KEY_ID> --eab-hmac-key <EAB_HMAC_KEY>  --manual --preferred-challenges dns certonly
```

I would like to contribute the work for Traefik to support this use case, but wanted to pass it by the team first to make sure 1) it's something you're open to and 2) that I'm making a PR that is likely to actually be merged (my decisions/design is appropriate).

## Proposal

My proposal is to add configuration to the ACME provider (TOML version)...

```toml
[certificatesResolvers.myresolver.acme]
  [certificatesResolvers.myresolver.acme.eab]
    keyId = "the key id"
    hmacFile = "/file/path/to/the/hmac/secret"
```

That looks like an update to the `Configuration` struct in the `pkg/provider/acme/provider.go` file. Seems fairly straight forward.

At that point, it's up to register the cert the right way. Based on what I can figure out (I'm still fairly new to go), it looks like the lego library has a separate `RegisterWithExternalAccountBinding` method that would be used instead of the `Register` method on the line below. Seems like a fairly straight forward update to make.

https://github.com/containous/traefik/blob/73ca7ad0c195cb752147a36fba7c715aaa09e2e8/pkg/provider/acme/provider.go#L233. 

Then of course there are the docs, which are pretty straight forward too.

## Questions

- I'd like this to work in both the Traefik 1 and 2 versions. What's the proper way to make a PR to support that? 
- What sorts of tests should we have here? 

Feedback/thoughts welcome!

**Comment by mpl** [comment]
@mikesir87 Hello, as long as you see the issue labelled as a proposal, it means we haven't had time to consider it, and that the corresponding PR probably won't get much more attention either.

We can preemptively answer your first question though: as this would be a new feature (and not a bug fix), it won't get into Traefik v1 (which only gets maintenance changes).

**Comment by mikesir87** [comment]
Thanks @mpl! I'm happy to contribute this to only the v2 branch of work. No problem there.

Curious... is there any sort of process to help a proposal advance beyond being a proposal?

**Comment by mpl** [comment]
Not really. The main factors for advancement speed are 1) how well it fits with our roadmap, 2) how complex it is, 3) how much traction the proposal gets. Just be ready to answer questions and feedback.

**Comment by delfer** [comment]
It would be nice to use Traefik with https://zerossl.com/

**Comment by rembart** [comment]
Since a few months, a large number of academic institutions have a new CA that provides ACME with a required external account binding, this feature will get a lot of attention. We already patched it in a traefik, basically the changes proposed by @mikesir87, works quite nice.

**Comment by aufomm** [comment]
> Since a few months, a large number of academic institutions have a new CA that provides ACME with a required external account binding, this feature will get a lot of attention. We already patched it in a traefik, basically the changes proposed by @mikesir87, works quite nice.

Hi Rembart, can you please share some information about how you patch Traefik to support EAB? Thanks

**Comment by fnbk** [comment]
Thanks @mikesir87, @rembart for putting up the initial work.

I just fixed a small compiler error in https://github.com/fnbk/traefik/commit/384e306fd65f0a4f70ef7eb7ede7ee80b11525c9 so that I was able to build an image and test it with [ZeroSSL](https://zerossl.com/) and it works partially.

traefik settings:
```
- --certificatesresolvers.customer.acme.caserver=https://acme.zerossl.com/v2/DV90
- --certificatesresolvers.customer.acme.email=florian@mail.com
- --certificatesresolvers.customer.acme.storage=acme.json
- --certificatesresolvers.customer.acme.httpchallenge.entrypoint=web
- --certificatesresolvers.customer.acme.eab.kid=EX89wkuqGA2cFv7vtBOXbw
- --certificatesresolvers.customer.acme.eab.hmacEncoded=8EGEqdMXR973ZWfwcGkFmBjahFTHt8ymskfl3twwK24Us0eeJPNJ2YXiB00bys1aTUwm7HrRGaa1WARjCuaVKQ	
```

Traefik is able to generate an certificate with EAB credentials using the ZeroSSL API:
```
time="2020-09-18T23:48:00Z" level=debug msg="Building ACME client..." providerName=customer.acme
time="2020-09-18T23:48:00Z" level=debug msg="https://acme.zerossl.com/v2/DV90" providerName=customer.acme
time="2020-09-18T23:48:00Z" level=info msg="Register with external account binding" providerName=customer.acme
time="2020-09-18T23:48:00Z" level=debug msg="legolog: [INFO] acme: Registering account for florian@mail.com"
time="2020-09-18T23:48:01Z" level=debug msg="Using HTTP Challenge provider." providerName=customer.acme
time="2020-09-18T23:48:01Z" level=debug msg="legolog: [INFO] [cq.f20.connected-quality.com] acme: Obtaining bundled SAN certificate"
time="2020-09-18T23:48:01Z" level=debug msg="legolog: [INFO] [cq.f20.connected-quality.com] AuthURL: https://acme.zerossl.com/v2/DV90/authz/wjgqK7FKw53GWdhUqwRqug"
time="2020-09-18T23:48:01Z" level=debug msg="legolog: [INFO] [cq.f20.connected-quality.com] acme: use http-01 solver"
time="2020-09-18T23:48:01Z" level=debug msg="legolog: [INFO] [cq.f20.connected-quality.com] acme: Trying to solve HTTP-01"
time="2020-09-18T23:48:01Z" level=debug msg="Unable to split host and port: address cq.f20.connected-quality.com: missing port in address. Fallback to request host." providerName=customer.acme
time="2020-09-18T23:48:01Z" level=debug msg="Retrieving the ACME challenge for token Gf0X-ho8LNlUyUdE7WinGKcJ_13jLlDJXmBMTJRD2Qc..." providerName=customer.acme
...
time="2020-09-18T23:48:13Z" level=debug msg="legolog: [INFO] [cq.f20.connected-quality.com] The server validated our request"
time="2020-09-18T23:48:13Z" level=debug msg="legolog: [INFO] [cq.f20.connected-quality.com] acme: Validations succeeded; requesting certificates"
time="2020-09-18T23:48:16Z" level=debug msg="legolog: [INFO] Wait for certificate [timeout: 30s, interval: 500ms]"
time="2020-09-18T23:48:17Z" level=debug msg="legolog: [INFO] [cq.f20.connected-quality.com] Server responded with a certificate."
time="2020-09-18T23:48:17Z" level=debug msg="Certificates obtained for domains [cq.f20.connected-quality.com]" providerName=customer.acme routerName=f20-whoami-9a86afc01f10a9b8be4e@kubernetescrd rule="Host(`cq.f20.connected-quality.com`) && PathPrefix(`/whoami`)"
```

Well it only works for the first time when a set of EAB credentials are used. Restarting the container will lead to an error and an invalid certificate!

```
time="2020-09-18T23:45:37Z" level=error msg="Unable to obtain ACME certificate for domains \"cq.f20.connected-quality.com\": cannot get ACME client acme: error: 400 :: POST :: https://acme.zerossl.com/v2/DV90/newAccount :: urn:ietf:params:acme:error:malformed :: [External Account Binding] The account is not awaiting external account binding, url: " providerName=customer.acme routerName=f20-whoami-9a86afc01f10a9b8be4e@kubernetescrd rule="Host(`cq.f20.connected-quality.com`) && PathPrefix(`/whoami`)"
```


So in my case the ECMA process with EAB works when starting the container the first time, but fails when renewing the certificate. Maybe it works with other SSL providers.

**Comment by ldez** [comment]
With ZeroSSL, for the moment I haven't tested yet with other providers but I'm thinking that is expected behavior, the binding between an account and the key can only be done once.

- If you keep the `acme.json` file, containing the account information, after the first registration, you will not have any issue.
- If you don't have any account information in the `acme.json` or already used the EAB credentials for something else, you have to create new EAB credentials, because the previous binding is not reused.

This is not the best behavior, I am currently working on the possibility of reusing the previous credentials without the need to create new credentials if you don't have the information in the `acme.json`.

**Comment by mikesir87** [comment]
I've had the same experience using `cert-manager` with InCommon (sectigo). Once the binding occurs to create the ACME account, those credentials are burned. They're effectively one-time use. So, yes... hanging onto the ACME account info is definitely important when using EAB.

**Comment by rembart** [comment]
Sorry for the late response, I'm currently involved in other projects and will not find the time to do a proper pull request soon (I'm not that into the traefik source code)

**Comment by ldez** [comment]
@rembart thanks, I will able that.

**Comment by chris13524** [comment]
This will be important for those needing to support older devices and need to use an alternative certificate authority: https://letsencrypt.org/2020/11/06/own-two-feet.html

**Comment by ldez** [comment]
Hello @chris13524 EAB has not relation with the root certificate. To handle the change you have to use https://doc.traefik.io/traefik/v2.3/https/acme/#preferredchain

**Comment by chris13524** [comment]
@ldez I was saying that demand for the EAB feature in Traefik has risen because of the need to use alternative certificate authorities (such as ZeroSSL, which requires EAB) in order to support older devices. Switching to the other chain as Let's Encrypt suggested (and you linked to) only works for 6 months, whereas switching to ZeroSSL for my CA needs will support older devices for much longer.

I believe this is related because this use-case for EAB could affect it's implementation in both Traefik and other ACME clients/proxies, especially for enterprises that really need to support those older Android devices going forward while still using ACME protocol.
