### ISSUE TITLE
Tune k8s providers clients user agent

### ISSUE THREAD

**Issue by sylr** [traefik/traefik#7391]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

The user agent used to talk to kubernetes is currently set to the default value which looks like this (taken from the k8s api-server metrics).

<img width="1014" alt="Fullscreen_07_10_2020_09_31" src="https://user-images.githubusercontent.com/153052/95301334-be82a080-0880-11eb-9978-e06b550e45fb.png">

Tuning this could improve our ability to observe traefik's behavior towards the api-server by:

- having a correct version number
- differentiating the ingress from the crd provider

I'm currently crafting a PR.

**Comment by rtribotte** [comment]
Hello @sylr,

I see that your have already make the PR.
Nevertheless, I see that your current proposal (through the reading of your PR), is to tune the user agent in a fixed manner.
The actual form looks ok, but i'm wondering if the customization of the user agent should be configurable ?
For instance, maybe a custom identification parameter would allow to differentiate multiple identical versions of Traefik instances.

Since it's more a discussion on your proposal that i want to have here, i'll wait for that to interact within the PR.

Anyway, thanks for your contribution !

**Comment by rtribotte** [comment]
Hello @sylr,

I see that you have already made the PR.
Nevertheless, could you explain your use case, why do you need this ? Since it's more a discussion on your use case that i want to have here, i'll wait for that to interact within the PR.

Thanks for your contribution !

**Comment by sylr** [comment]
I'd like to be able to compare the "pressure" traefik puts on the api-server between two versions.
