### ISSUE TITLE
Support FastCGI protocol

### ISSUE THREAD

**Issue by tcoupin** [traefik/traefik#753]
I want to use traefik as loadbalancer in front of some rok4 intances (http://www.rok4.org/documentation/rok4-deploiement).

Rok4 only support fastCGI. It would be nice if traefik support this protocol :)

**Comment by f3l1x** [comment]
It would be great!

**Comment by mvdstam** [comment]
Definitely +1 -- this would make it much simpeler to deploy applications that are, for example, based on `php:7-fpm`.

**Comment by errm** [comment]
This is possible, but I would need to be convinced of a few things.

* are the fcgi libarie(s) available for go (I know of one) good enough, or are we going to end up inventing a wheel.

* is fastcgi over the network even desirable, I know it's possible, but most setups I have seen use unix sockets.

* will we be able to support all of the features we have with http using fastcgi without making to many modifications?

**Comment by ckeeney** [comment]
Right now, I use Caddy in front of fastcgi.  [Here](https://github.com/mholt/caddy/pull/1264) is the pull request merging in fastcgi support into caddy.  It looks like, for whatever reason, the Caddy contributors wrote their own fastcgi package.

I use it over network.  I know most use unix sockets, but with docker using the network is more straightforward.  I don't know how you would use unix sockets without just mounting a socket from the host, but I prefer my docker deployments not rely on host resources.

**Comment by mvdstam** [comment]
@errm Sockets are, in theory, a bit faster than using TCP, but TCP is way more scalable by default. With solutions like Docker Swarm combined with the service discovery capabilities that Traefik has to offer, you could have many containers listening on `:9000` for the same service, and thus have an extremely flexible and scalable solution.

Secondly, it would be neat if you could just add a label `traefik.proto=fastcgi` to a container, which would mean that Traefik would proxy the incoming HTTP requests via FastCGI to the underlying container(s).

**Comment by Multiply** [comment]
We could also use it in our testing and even production environments, as we use php-fpm for some microservices.

Right now I have setup nginx in front of php-fpm, and then traefik in front of nginx. We could really cut some overhead by simply using fastcgi from traefik to php-fpm.

If you point me in the right direction, I'd be happy to contribute to this feature.

**Comment by tcoupin** [comment]
- net/http/fcgi: Currently only the responder role is supported => do somebody know a fastcgi client package ?
- if the protocol is set at the server level, I think [oxy/forward](https://github.com/vulcand/oxy/blob/master/forward/fwd.go) must be modified before traefik

**Comment by rkgrep** [comment]
Any plans on implementing this feature?
It would be really great to have it!

**Comment by htvennik** [comment]
Just found this: https://github.com/yookoala/gofast
Would that help?

**Comment by Yivan** [comment]
Hello, +1 for this one too.
I just switch from using jwilder/nginx-proxy for docker to traefik, all went ok, and the only settup missing is fastcgi. It has been added recently on jwildr/nginx-proxy: https://github.com/jwilder/nginx-proxy/pull/861
Thanks.

**Comment by danielgrabowski** [comment]
The same here. I tried jwilder/nginx-proxy on Docker Swarm but it lacked configuration capabilities Traefik has. But... I need PHP-FPM support.

**Comment by whlsxl** [comment]
I think traefik still not support fastCGI, should we mark this as open topic?

**Comment by whlsxl** [comment]
fastcgi is the only reason I haven't switch from nginx to traefik 😂

**Comment by jlelse** [comment]
I'm currently using Caddy with a handwritten Caddyfile, but I would like to switch to automatic Traefik proxy. Only fastCGI is holding me back. Are there any official updates about this topic.

**Comment by Yivan** [comment]
@geraldcroes Could you just please give us some roadmap on this improvement, if there is any ? It would help us to plan things. Do you think there is a chance this will be implemented ? I hope really it will.
Thanks again for the great work you make on Traefik, we really enjoy it, this is the only feature missing ; )

**Comment by geraldcroes** [comment]
We're listening ... but there is no ETA for this issue for the moment.

**Comment by Yivan** [comment]
@geraldcroes Thanks a lot for your return. Ok, i hope this improvement will be accepted and scheduled on TODO ; )
Have a great day.

**Comment by whlsxl** [comment]
For `wordpress`, it have a problem,  usually `fastcgi` just host `php` files, the static files need to be  host by traefik(or other reverse proxy) for performance. but now docker can't change volume mount by  `docker.sock`. 
Now I need `nginx` between `traefik` and `fastcgi`, it will cost less than 10M memory. for now it OK, but not perfect. But can't get other solution 😂😂😂

**Comment by tcoupin** [comment]
I work on this issue: https://github.com/tcoupin/traefik/commit/6effcb928570160a046f71e6571460c528e03d1c

It is not finish and I need some advice from traefik experts: 
- can this way be the right one ?
- I don't use clients pool feature of gofast package since it will be manage at the rr loadbalancer. Agree ?
- Do you know a simple way to pass from a http.responsewriter to a http.response ?

**Comment by bensonfx** [comment]
Are there any official updates about this topic?

**Comment by Yivan** [comment]
@tcoupin Thanks a lot for invetigating your time to propose a solution.
I cannot help you on the code / your question, as i am not an expert of traefik code.
I really hope some people or trafik core team member could assist you in this task.

Best regards.

**Comment by EmixMaxime** [comment]
Same here, I'm giving a try to traefik but it seems very weird... I'm wondering if traefik doesn't add some complexity, because I'll have to have it in front of nginx which is in front of my apps... Doesn't seems to be a good solution is it?

**Comment by Yivan** [comment]
@tcoupin , any news about merging your changes ( https://github.com/tcoupin/traefik/commit/6effcb928570160a046f71e6571460c528e03d1c ) ?
Best regards

**Comment by Elegant996** [comment]
It's incomplete so there would be nothing to merge.

**Comment by lucca-cardial** [comment]
Looking forward

**Comment by waahhhh** [comment]
We should concentrate on implementing it in version 2 as a router.

**Comment by guyromb** [comment]
Any news on that?

**Comment by mwmahlberg** [comment]
> [Write programs that do one thing and do it well.][wp:philo]
> *Peter H. Salus*

I am against that. While it sounds great on paper, I see several problems.

Traefik is an edge router/ingress controller (for k8s) which happens to understand the intricacies of http(s) and provides SSL termination. By the same logic that it makes deployment easier, one could argue that it should be able to provide support for [AJP][wp:ajp], [rack][wp:rack] or [WSGI][wp:wsgi] or `TheNextBigSuperLightweightWhateverProtocolImplementedBySomePetLanguage`

Even just adding the support for FCGI would not only clutter the code and subsequently increase the work needed to maintain it beyond the actual code changes by adding a layer of complexity, but work needed for documentation  and integration testing, too -- you would want to make sure it runs with at least php-fpm in several versions, distribution specific patched packages, the FCGI client libraries of the most important languages etc. pp.

And all this for a feature that is readily available and properly maintained, documented and tested in other projects. Just to save a few lines of config files, and a tiny bit of latency and a negligible amount of RAM compared to the load.

>  Premature optimization is the root of all evil (or at least most of it).
> *Donald Knuth*

I dare to postulate that in every web application there are possibilities for optimization that exceed the effects of this proposal being implemented by orders of magnitude.

[wp:philo]: https://en.wikipedia.org/wiki/Unix_philosophy
[wp:ajp]: https://en.wikipedia.org/wiki/Apache_JServ_Protocol
[wp:rack]: https://en.wikipedia.org/wiki/Rack_(web_server_interface)
[wp:wsgi]: https://en.wikipedia.org/wiki/Web_Server_Gateway_Interface

**Comment by guyromb** [comment]
@mwmahlberg the demand is high enough to support this and the end justifies the means

**Comment by mwmahlberg** [comment]
@guyromb By that logic, we should implement FCGI support into the Linux kernel.

**Comment by gregorybrzeski** [comment]
@mwmahlberg I understand your view point and agree partially with it. However demand is high and I could understand why. The most important question is how to solve it without just simply saying it's not going to happen.

What about finding a way to support those demands using some pluggable code structure ? Maybe version 2 architecture which allows for middlewares can be used here ?

**Comment by mwmahlberg** [comment]
@gregorybrzeski I have not looked into the architecture of v2, yet. However, there is a pluggable feature system, already. It transfers HTTP requests over networks, uses connection keepalives by default, is loadbalanceable out of the box and you even can use various implementations of the same feature. Taking FCGI as an example, you can use implementations from [rather heavy](https://httpd.apache.org/docs/2.4/mod/mod_proxy_fcgi.html) to [extremely lightweight](https://www.hiawatha-webserver.org/howto/cgi_and_fastcgi). ;)

On a slightly more serious note: reinventing the wheel over and over again does not add value. The fact that Traefik explicitly is to be understood as an edge router and does not include a kitchen sink, a coffee machine and a massage chair, but limits itself to the bare necessities is what made us choose it over nginx as an ingress controller, for example.

**Comment by rogeriolino** [comment]
At the begining I was in favor of doing this feature (I'm a PHP developer). However, with the evolution of the PHP language and PHP-PM project, I see that the PHP apps is going to be self served like Go, node, dotnet core, etc. What will be unnecessary use of fgci in this case.

Then, I'm agree with @mwmahlberg at the fact of add complexity into Traefik code against the benefits of it in a near future.

**Comment by phroggyy** [comment]
This functionality was just added to nginx-ingress https://github.com/kubernetes/ingress-nginx/pull/4344

**Comment by mwmahlberg** [comment]
Is this discussion still open or was there a decision made?

**Comment by geraldcroes** [comment]
The issue is still open, no decision has been made.

**Comment by porschberg** [comment]
Running mybb forum software with traefik as reverse proxy needs this feature too.

**Comment by mwmahlberg** [comment]
@porschberg I am not too sure wether traefik, as good as it it, is the right tool for the job, then. And again, where to stop, then? WSGI? SCGI? Also please see https://github.com/containous/traefik/issues/753#issuecomment-503986392
The "One server to rule them all" approach lead to the monstrosity httpd is nowadays.

**Comment by mxmaxime** [comment]
I understand your meaning @mwmahlberg 
The vision is, Traefik should handle incomming request and route them (Edge Router), and that's all. Some handy features like SSL, Auto Service Discovery, that helps the main feature: "Edge Router". That makes sense to me.

So we have our services, nginx or apache or anything else and Traefik in front of them.

By huge curiosity, is WSGI huge to implement? Thank you 😄

**Comment by mwmahlberg** [comment]
@mxmaxime Probably not - but that is not the point.

I _can_ understand why people would want to simply expose their fcgid and let the infrastructure (of which Traffic _is_ a part of) handle the rest. It is compelling and minimalist.
However, imho, there are several huge misconceptions coming with that.

1. _**"I have a TLS certificate on my edge router, I am safe and can use an unsecured protocol for intra-cluster communication"**_
No, you are not and no, you should not. The thing is that you would have unsecured traffic between your edge router and FastCGI and SCGI instances. Implementing FastCGI into Traefik support would not only make an inherently insecure deployment possible, but actually _promote_ it. What you actually need to do is to set up a TLS communication between Traefik and whatever webserver you choose and then have a local-only communication between your Webserver and your FastCGI process. In case of Kubernetes, you can leverage the [k8s certificate API](https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/) between Traefik and your http server and use [multiple containers within the same pod](https://kubernetes.io/docs/concepts/workloads/pods/pod-overview/#how-pods-manage-multiple-containers) for your FastCGI setup.
2. _**"It is easier!"**_
Maybe, but only if you take a subset of what a FastCGI requires and/or provides into account. How would you handle the process spawning? Handling of static assets? Shall Traefik do that, too? How about access logs? Websockets? That would all be _possible_, but it would further blur the line between the workloads and the infrastructure.
3. _**"It is not much work to implement!"**_
Seriously, if you open that box of pandora, you need to make a full fledged webserver out of Traefik, since as long as it is not, there will be a gazillion bug reports for this and that missing feature required to run a FastCGI environment behind Traefik properly. A feature you put in the wild needs maintenance, which is expensive (be it time or money wise, or both). Worse, effort would be put into reinventing the wheel. To what end? To save a process in a container in a pod, to stay in k8s parlay? With that processes aka existing HTTP servers already having FastCGI implemented, tested and supported? 

And again, why stop at FastCGI?

With implementing FastCGI, the door would be opened to similar feature reguests regarding everybody's and their dogs favorite transfer protocol. Oh, I would like AJP.

**Comment by drzraf** [comment]
Even that being said, nothing keeps maintainers from providing a **minimal** and **well-delimited** implementation with a set of restriction which would definitely keep 10% of users from it but satisfy 90%. Eg:
- No SSL down the road
- No complex thread management
- No caching, etags & co
- No websocket
- Using the (unforked) [official fcgi Go package](https://github.com/containous/traefik/issues/753#issuecomment-598610912) only
- WIth no more than X hundreds additional lines of code

Even with these constraints I'd still be interested in have it... as > 90% of the above 135 thumb-upper ;)

**Comment by mwmahlberg** [comment]
@drzraf Forgive me, but an argumentum ad populum is a fallacy at best and a sophism at worst. However, if it is not much work, I am sure a pull request will be considered.

**Comment by tuxmainy** [comment]
Hi,
+1 for FastCGI: Another app that it could used for is nextcloud.

Anyway, beside personal views is there any plan to implement this? This ticket is 4 years old. If you don't plan to implement this it's more or less ok for me because it's your personal time and product. But then please close this issue. Don't give me hope ;)

![grafik](https://user-images.githubusercontent.com/27895250/95650547-8e3b3c00-0ae4-11eb-8ed8-9824ae0b9fe5.png)

regards
Daniel

**Comment by bd8392** [comment]
+1 for fastcgi (for nextcloud). This would be really cool!

**Comment by andrei-dascalu** [comment]
Well, I'm also interested in this conversation.

In fact, this is the one thing that's preventing wide-scale adoption of Traefik (as opposed to Nginx Ingress, which supports FCGI) in our outfit as we have lots of PHP services. We've experimented a lot but since there's a bit of legacy-ish code involved, the solution was to put them behind an Apache or Nginx internally, but the FPM was still exposed internally. It's a limitation that we have to live with for now. Despite the rise of PHP-PM or Roadrunner, it's long-term work to migrate. 

It would be great if Traefik will eventually support it.

**Comment by Waltibaba** [comment]
@mwmahlberg brought some great arguments.
In case nobody noticed, this conversation is the definition of feature creep.

**Comment by milewski** [comment]
I think this issue could be closed, The rise of Swoole and Roadrunner has proven that FastCGI is not that fast. And now with the release of Octane, I think everyone who was once here looking for a way to remove the "middle man" (NGINX/CADDY/APACHE) has gotten a much better solution that does not require FastCGI at all.. leave Traefik slim.. it is good the way it is..

**Comment by couling** [comment]
Well I came here in hope, but sadly no support yet...

@mwmahlberg Forgive me for being an argumentative so-and-so... I'm interested in this statement and it's follow up arguments to a similar effect.  

> Traefik is an edge router/ingress controller (for k8s) which happens to understand the intricacies of http(s) and provides SSL termination. By the same logic that it makes deployment easier, one could argue that it should be able to provide support for [AJP](https://en.wikipedia.org/wiki/Apache_JServ_Protocol), [rack](https://en.wikipedia.org/wiki/Rack_(web_server_interface)) or [WSGI](https://en.wikipedia.org/wiki/Web_Server_Gateway_Interface)
>
> mwmahlberg

mwmahlberg is right to suggest that it is not Traefik's place to implement such things as WSGI, AJP and Rack.  These are all language specific frameworks for building web apps on in their respective language.

But I wouldn't compare FastCGI in with WSGI, Rack or AJP.  FastCGI isn't really a language framework at all.  It's an IPC protocol designed to bridge between web server and content software (of any written in any language).  That is, as a protocol, it's much more related to HTTP than it is WSGI.  Wikipedia:

> FastCGI is a binary protocol for interfacing interactive programs with a web server. 

It's not lost on me that the majority of people who find their way to this issue are looking to run PHP-FPM.  It's also not lost on me that FastCGI is an aging technology with fewer and fewer uses these days.  To my mind, that and only that justifies mwmahlberg's point of view.

If other's find their way here looking to support non PHP FastCGI apps, they might like to speak up, as this would better justify the feature.

**Comment by computator** [comment]
I've been following this issue for awhile, and this is absolutely my viewpoint as well. It's a language agnostic protocol not tied to a specific language, and thus, imo, not unreasonable for traffic to support. I don't need any fancy features or anything either, just direct routing/passthrough of requests via FastCGI. If I need extra things such as static asset handling or any fancy config stuff or whatever, then of course I would need to add in a full featured web server that is intended to do that.

**Comment by tfny** [comment]
Hello everyone!  This issue is a candidate for a bounty during the Traefik Proxy 3.0 Hackaethon!  

This means that if the design and POC or the fully fleshed-out PR for this issue is accepted in the Hackaethon, the person or team behind doing it will receive $250 as well as a chance at the Grand Prize of $1000! 

All accepted PRs and designs will receive a tshirt and stickers.  

To learn more about the Hackaethon, check out our [blog post](https://traefik.io/blog#:~:text=Hack%20Into%20the,Read%20more) that covers the goals, rules, scoring criteria, and dates in detail. 

To join us, [sign-up here](https://info.traefik.io/traefik-proxy-3-0-hackaethon?cta=pop)!

**Comment by ddtmachado** [comment]
Hey everyone, we're opening a [new issue proposal](https://github.com/traefik/traefik/issues/9521) based on the proof-of-concept work from the Hackathon, as originally described in [this comment](https://github.com/traefik/traefik/issues/753#issuecomment-1275872678).

We believe this is the best approach to **validate** that what can be delivered with Traefik will still be beneficial for the users requesting it, given its limitations, mainly that Traefik is not able to serve static resources so you still need a web server/CDN.

Thanks for everyone that engaged in discussions and helped move this forward so far. And from now on you can react, add your thoughts, comments and suggestions in the new proposal.
