### ISSUE TITLE
UDP traffic doesn't get loadbalancing by traefik

### ISSUE THREAD

**Issue by debu99** [traefik/traefik#7697]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
We run 2.3.3 in EKS to load balance DNS requests from outside, and we use NLB as an external loadbalancer, the dns request will go through several CoreDNS pods in K8s

### What did you expect to see?
The request should go to one of the CoreDNS pods and the load should be distributed

### What did you see instead?
Only 1 CoreDNS pod got high cpu usage, the other scaled pod by HPA almost no load

### Output of `traefik version`: (_What version of Traefik are you using?_)
2.3.3

```
(paste your output here)
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
EKS, CoreDNS pods, Traefik, AWS NLB

```toml
# (paste your configuration here)
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
(paste your output here)
```

**Comment by debu99** [comment]
![image](https://user-images.githubusercontent.com/25805758/102735738-2a53b000-437e-11eb-9bdf-e82aeac75c17.png)
Need 15-20 mins to distribute the traffic to other pods....

**Comment by notsureifkevin** [comment]
Hey @debu99, thank you for submitting this issue. In order to better understand what's happening here, would it be possible for you to provide a minimally reproducible example? In this case, we would need the following:

* eks version and setup details (multiple az, private/public, etc)
* nlb configuration (timeouts, listeners, target groups, etc)
* traefik configuration (entrypoints)
* services and ingress configuration (udp service and rules)
* script or load generator that replicates the issue and instructions on how to reproduce

Without more information, it is difficult for us to reproduce and help you troubleshoot this issue.

**Comment by Legogris** [comment]
Possible related to https://github.com/traefik/traefik/issues/7430

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
