### ISSUE TITLE
Path based Routing is not working

### ISSUE THREAD

**Issue by satheshs** [traefik/traefik#7705]
In path-based routing when i used traefik.frontend.rule.type: "PathPrefixStrip", it is not stripped off the prefix.

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: path-based
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: "PathPrefixStrip"
    traefik.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - host: cheeses.minikube.com
    http:
      paths:
      - path: /stilton
        backend:
          serviceName: stilton
          servicePort: http
      - path: /cheddar
        backend:
          serviceName: cheddar
          servicePort: http
      - path: /wensleydale
        backend:
          serviceName: wensleydale
          servicePort: http

Could you please suggest me how can we do this.

**Comment by kevinpollet** [comment]
Hi @satheshs and thanks for your interest in Traefik!

We dedicate the issue tracker to bug reports and feature requests only.

As your issue seems to be a question, please join our [Community Forum](https://community.containo.us/) and reach out to us on the [Traefik section](https://community.containo.us/c/traefik). In the meantime, you can double-check [Traefik's documentation](https://docs.traefik.io/).

Therefore, we will close this issue accordingly.
