### ISSUE TITLE
Support multiple IpWhitelist middlewares for a service

### ISSUE THREAD

**Issue by canidam** [traefik/traefik#7720]
### Do you want to request a *feature* or report a *bug*?

Feature

### What did you expect to see?

I have a requirement to allow multiple IPs of different providers (e.g, AD, AWS, GCP..) to a service. I was trying to create a middleware for each provider, with the relevant IPs in it. Since the list is large, I manage it using a file:

```
[http.middlewares.provider1.ipWhiteList]
    sourceRange = [ ... ]

[http.middlewares.provider2.ipWhiteList]
    sourceRange = [ ... ]
```

I then tried to apply multiple middlewares on the service on docker:

`"traefik.http.routers.myservice.middlewares": "provider1@file,provider2@file"`

While I thought it would work - it didn't, I googled a bit and encountered few similar issues, but no solution.

It would be good enhancement if before applying the middlewares, if there are multiple ipWhiteList middlewares, merge them to a single list before applying. It will make the ACL management much easier when there are different lists of IPs needs to be allowed.

As a workaround - I merged the different lists into a single one in the configuration, and applied that. These lists are expected to change, having this feature would make it so much easier to manage.

**Comment by rtribotte** [comment]
Hello @canidam,

Thanks for your interest in Traefik!

It's indeed a limitation. You can use another provider for your middleware definition that could make it easier to manage changes of the list over time (for instance a KV provider).

Unfortunately, we cannot introduce this specific behavior since this would not be expected if you indeed want to chain IPWhitelist middlewares with for instance a different depth strategy, and it would not make sense to merge the two middlewares if their configurations are diverging.

I will decline this issue accordingly.
