### ISSUE TITLE
Not all log entries are formated as expected

### ISSUE THREAD

**Issue by chris-askbrian** [traefik/traefik#7723]
### Do you want to request a *feature* or report a *bug*?

Bug

### What did you do?
I enabled debug logging with json log format on.

### What did you expect to see?
**All** log entries to be in json format.

### What did you see instead?
The first "Configuration loaded from flags." info log entry is in "common" format.

### Output of `traefik version`: (_What version of Traefik are you using?_)

```
Version:      2.3.6
Codename:     picodon
Go version:   go1.15.6
Built:        2020-12-17T16:34:27Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration (arguments, toml, provider, platform, ...)?
Runs in a docker container with cli configuration:
```
--log.format=json --log.level=DEBUG"
```

### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)

```
traefik    | time="2021-01-05T15:15:23Z" level=info msg="Configuration loaded from flags."
traefik    | {"level":"info","msg":"Traefik version 2.3.6 built on 2020-12-17T16:34:27Z","time":"2021-01-05T15:15:23Z"}
```

**Comment by rytsh** [comment]
Traefik version 2.6.0, still same issue

**Comment by rtribotte** [comment]
Hello,

While coming across this issue, I wondered why the linked PR didn't succeed to address it.
The answer is not obvious but quite simple.

While there are solutions to apply the correct format for this type of log (`Configuration loaded ...`), because configuring the logger as soon as the static configuration is parsed seems achievable. But there is no solution to take into account the log configuration when an error occurs during the static configuration loading.

So, having the first log printed in the correct format is not solvable in every situation.
In addition, from a pure design perspective, the configuration loaders, which are producing this log, should not apply the static configuration (such as configuring the log format).

Because there is no solution to address the issue completely, and also because this issue has never had a lot of traction, I close it.
Nonetheless, anyone is welcome to ask to reopen it, if it feels wrong.
