### ISSUE TITLE
Add metric for request size

### ISSUE THREAD

**Issue by crunchtime-ali** [traefik/traefik#7804]
### What did you expect to see?

We need to track the network traffic going through Traefik to be able to be able to properly bill the cost for each service/product. Therefore, we need the request size for the already existing metric `reqsCounter`.

Would this be sufficient to determine the aggregated request size per Ingress (in K8s)?
Are you willing to implement this or accept a PR?

**Comment by rtribotte** [comment]
Hello @crunchtime-ali,

Thanks for your interest in Traefik!

Unfortunately, we are not going to accept this metric if it means to read the request/response body. This is not something Traefik does and will do, because it would considerably impact performances.

Thus we are open to hearing about a solution that would not impact performances.

Also, there is probably a better solution on the service/product side.

I'll label this issue as a proposal accordingly.

**Comment by crunchtime-ali** [comment]
My other plan was building it as a plugin for Traefik (if that is even possible). However, we can't afford influencing the performance negatively of Traefik which is our edge proxy of choice in a K8s environments (Ingress controller).

> Also, there is probably a better solution on the service/product side.

Are you talking anything specific? Coming back to our K8s environment that is the only way (besides having sidecars next to each pod) that comes to mind. The Amazon VPC-CNI-Plugin could probably help with a lot of tinkering but that has various limitations we don't want to cope with.
