### ISSUE TITLE
Failover to ZeroSSL from Let's Encrypt?

### ISSUE THREAD

**Issue by dm17** [traefik/traefik#7935]
Caddy now has this feature where if it can't get a cert from one provider, then it will try the next. For example, this works with both ZeroSSL & Let's Encrypt. Is there a way to do this in Traefik that I'm missing?

If not, then I think it is a worthy feature to include.
Thanks!

**Comment by rtribotte** [comment]
Hello @dm17,

Thanks for your interest in Traefik!

I understand that you are requesting a feature that would allow you to set up a fallback certificate provider in case of failure of the acquisition of certificates with a first provider.
Because you are referring to [Caddy](https://caddyserver.com/), which is a ZeroSSL product, it's important to notice that it's using a specific implementation using the ZeroSSL API and have ZeroSSL in the list of theirs default ACME-compatible CAs in addition of Let's Encrypt.

[Let's Encrypt SLA](
https://letsencrypt.org/2021/02/10/200m-certs-24hrs.html) is quite good actually, and the need for a failover doesn't raise with the most common use cases. The renewal period is long enough to overcome a failure.

Also, there are no certificate provider specific features implemented by Traefik. To keep this agnostic approach, starting supporting ZeroSSL would also mean opening the door to support all other providers and will add substantial maintenance regarding API interactions.

Unfortunately, I'll decline your feature request for those reasons.
If you feel that I'm missing something here, please let me know.

**Comment by dm17** [comment]
> Hello @dm17,
> 
> Thanks for your interest in Traefik!
> 
> I understand that you are requesting a feature that would allow you to set up a fallback certificate provider in case of failure of the acquisition of certificates with a first provider.
> Because you are referring to [Caddy](https://caddyserver.com/), which is a ZeroSSL product, it's important to notice that it's using a specific implementation using the ZeroSSL API and have ZeroSSL in the list of theirs default ACME-compatible CAs in addition of Let's Encrypt.
> 
> [Let's Encrypt SLA](https://letsencrypt.org/2021/02/10/200m-certs-24hrs.html) is quite good actually, and the need for a failover doesn't raise with the most common use cases. The renewal period is long enough to overcome a failure.
> 
> Also, there are no certificate provider specific features implemented by Traefik. To keep this agnostic approach, starting supporting ZeroSSL would also mean opening the door to support all other providers and will add substantial maintenance regarding API interactions.
> 
> Unfortunately, I'll decline your feature request for those reasons.
> If you feel that I'm missing something here, please let me know.

That's fine - your explanation is important info for us.
