### ISSUE TITLE
HostRegexp should work with Letsencrypt

### ISSUE THREAD

**Issue by lifeofguenter** [traefik/traefik#7999]
httpChallenge/Letsencrypt should work with HostRegexp - it can just use the http-host header :)

**Comment by ldez** [comment]
Our implementation of ACME challenges never relies on HTTP headers, because they can be spoofed.

If you want to use `HostRegexp` can define your domains via the `domains` option of the router.

https://doc.traefik.io/traefik/v2.4/routing/routers/#domains

Next time, please follow the issue template.
