### ISSUE TITLE
Delay between new release and new Docker Hub image : why ?

### ISSUE THREAD

**Issue by semangard** [traefik/traefik#8213]
Hello,

The version 2.4.9 has been released but we are not able to find the 2.4.9 tag on Docker Hub.
Why don't you release both at the same time ?

Is Docker Hub your official docker repository ?

Regards

**Comment by SantoDE** [comment]
Hey @semangard,

Because the official images are maintained by docker, where we don't have an influence on. The only thing we can do is to open a bump PR, which we did [click](https://github.com/docker-library/official-images/pull/10400)

Once its merged, a couple hours later the new version will be on docker hub.
