### ISSUE TITLE
consulCatalog Provider: keep configuration / do not drop routes, middlewares or services on conflicting configurations

### ISSUE THREAD

**Issue by sirkjohannsen** [traefik/traefik#8256]
### Traefik drops the configuration during rolling upgrades using consulCatalog

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

What I wish to see is an option on the **consulCatalog** Provider to enable "keeping routes, middlewares and services online if the case of conflicting configurations arises". 

The issue is stated quite nicely here: https://community.traefik.io/t/router-defined-multiple-times-during-rolling-deployment/7517

The error in question here is:
`Service defined multiple times with different configurations`

This will happen if you do a rolling upgrade of services (we do it via HashiCorp Nomad) and the new version has a change in the routing rules, middlewares or loadbalancer definition and so on. 

The Problem at hand is that in this case the complete router, middleware and/or service is dropped completely from traefik.
So, during the rolling upgrade - the service is not reachable at all but returns traefiks 404 (in the best case) or matches on another route.

Would it be possible to **NOT** drop everything as soon as this error/situation occurs but maybe wait (a configure-able amount of time) for the conflict to be resolved and keep the old/current configuration during that time ? 
If this is possible, it would be great of course if this could be configured in the provider configuration.

Is anything like this planned ? Is it even possible ? And if not, could you please elaborate why ?

**Comment by rtribotte** [comment]
Hello @sirkjohannsen,

This behavior is indeed produced by design.
Traefik fetches all configurations from containers tags simultaneously and tries to merge them afterward.
When the merge operation detects identical resources definitions (routers, middlewares, services...), it drops them all.

So conflicts are avoided by dropping all resources defined multiple times.

As it has been pointed out, a solution is to name resources differently. Thus it implies having a process to handle that.

Another solution could be to manage a tag, that would act as a constraint to allow Traefik to consider the configuration from a container or not, by using the `constraints` option of the ConsulCatalog provider configuration.
In that scenario, you would "deactivate" and "activate" your containers during the rolling update.

Thus, the only zero downtime solution is to name routers, middlewares, and services differently, in order to avoid collisions.

Regarding a potential proposal, what do you suggest?
I understand, that keeping the previous configuration applied in case of conflicts until the convergence, would solve the rolling update case you've exposed.

**Comment by sirkjohannsen** [comment]
Hello @rtribotte,

Thank you very much for your reply.
I already figured this behavior was on purpose. 
Nonetheless - its not ideal for dynamic providers that support rolling updates ;) 
We are using HashiCorp Nomad to orchestrate our services and love the fact the we provide the traefik routing information as tags alongside the job/service definition.
I do not think that any of the 2 proposed solutions will be possible for us. 

Currently we are looking into using the consul-kv provider to define routers and middlewars that then route to the service `@consulcatalog` - sadly this will ALWAYS also generate the default router but it might work for us. Also - any configurations on `service` level will still have the same issue. 

A proposed solution would be to add a parameter to the provider (e.g. `keep_old_config_on_conflict` ) or something similar that would implement the described behavior to keep the previous routes/middlewares (for a certain amount of time ?)  during a conflict situation. 

Does that make sense ? 

Many thanks again for your reply,

Sirk

**Comment by rtribotte** [comment]
@sirkjohannsen Thanks for your answer!

It's pretty clear, and it does make sense.

For a certain amount of time, I would say this would not be manageable. Also from Traefik point of view, it wouldn't be easy to consider a resource (e.g: a router) as the previous one and another that would be considered as the new one.
Also because potentially a router can be defined more than two times.

With those considerations, the solution I would come up with is to prevent the application of the configuration if a conflict is detected. This way, the previous configuration would remain applied until the new configuration converges to a state without conflicts.

The only grey area for which I'm wondering is what constraint prevents from being an acceptable solution to change the names of the routers and services before applying the rolling update?
I come back to this because this is obviously the simplest way to manage rolling updates.
Do you think that Traefik should be capable of an automatic naming that would allow avoiding conflicts in that case?

**Comment by sirkjohannsen** [comment]
@rtribotte thinking about this more now - you might be right that defining new versions of routers and middlewares with a unique identifier might actually work. Still not sure about the `service` level configurations though but I will give it a try. 

Btw, how will traefik behave if there are 2 routers with the same routing definition (e.g. Host=my-host) ? 
Which router will take precedence ?

**Comment by rtribotte** [comment]
@sirkjohannsen Good question ;-)
In terms of routing, this can be an issue.

You'll have the priority of the router that will be taken into account to evaluate the first to try to match.
The priority is configurable, but it equals by default the length of the rule of the router.
A long rule is evaluated before a shorter rule.

Thus when the priority is the equivalent, the order is not guaranteed in any way, the first router in the list across routers with the same priority is simply evaluated first.

So if the configuration update doesn't alter the routing configuration or the priority, you'll end up with an uneven behavior if it creates two or more routers that can match the same request but route to different services.

In that case, controlling the priority is the only left option, but it's maybe not the more handful to manage.

**Comment by sirkjohannsen** [comment]
@rtribotte I know about the priority but we highly rely on the automated calculation of that value running >60 services with different routing rules. So I would rather not start touching the priorities.
I was honestly afraid of having multiple routers with the the same routing rules because I already expected the behavior to be unclear.
Since in our case this only means we might route to the old or new version during deployment, it should not be an issue.
I will conduct some tests and evaluate if this solution will work for us. 

Nevertheless - A builtin feature like described in this issue might make lives easier ;)

**Comment by sirkjohannsen** [comment]
Many thanks @rtribotte 
When using unique names for each service, router and middleware it works. 
There are ofc multiple service, router and middleware definitions active during the deployment which seems a bit odd but it works nonetheless.  
I will close this issue.

**Comment by pirogoeth** [comment]
Hello, I'm sorry to bump a closed issue, but I've started running into this exact issue.

We have a service mesh that has a registered backend service for with Traefik, via the Consul Catalog provider. Our services also register themselves with our service mesh via an external API. All of our applications are deployed with Nomad and registered with Consul Catalog, but describe their public ingress using router blocks (on the service's job file) and point the router to the service mesh's backend service. If we change anything on our service tags for the service mesh, or for any of our services, that resource will be dropped from Traefik's configuration during deployments, when the new and old tags are registered in the catalog.

Due to our setup, we can't just rename the routers or services, as that would require redeploying our entire stack. I think the `keep_old_config_on_conflict` option is super reasonable and would like to try to PR that. Would you/the team be open to a PR to add that configuration knob?

**Comment by sirkjohannsen** [comment]
@pirogoeth not sure if this helps you but we have / had the same issue. We still needed a "fixed" service name that could be discovered via consul service discovery - unrelated to traefik. 
So we simply register 2 services per task now.

nomad job config snippet:
```
...
            # Service for traefik routing
            service {
                name = "my-service-<dynamic version>"
                port = "http"
                tags = [
                    "traefik.enable=true",
                    # traefik middlewares
                    "traefik.http.middlewares.my-service-<dynamic version>-ssl-headers.headers.sslredirect=true",
                    # traefik.routers
                    "traefik.http.routers.my-service-<dynamic version>.rule=Host(`my-host.xxx`)",
                    "traefik.http.routers.my-service-<dynamic version>.middlewares=my-service-<dynamic version>-ssl-headers",
                 ]
            }

            # service for service-discovery via consul
            service {
                name = "my-service"
                port = "http"
                tags = ["my-service"]
            }
...            
```

In general I also still think it would be awesome to solve this on traefik side via a configuration option.

**Comment by pirogoeth** [comment]
@sirkjohannsen thanks for the suggestion, I appreciate it. I'm not sure that fully solves our issue, but I'll certainly be chewing on this for a bit.
