### ISSUE TITLE
The setting of accesslog should be dynamic

### ISSUE THREAD

**Issue by niaiwomattt** [traefik/traefik#8401]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

The setting of accesslog should be dynamic. I don't need accesslog most of the time. I only need it when there is a problem and debugging is needed, so I hope it can be set dynamically.

**Comment by rtribotte** [comment]
Hello @niaiwomattt,

Thanks for your interest in Traefik!

We gave some thought to your proposal and we conclude that the solution would be to be able to reload what is today the static configuration, which is not possible today.
Since it has been addressed by issue #1188, I'll close this issue accordingly as a duplicate.
