### ISSUE TITLE
Add Lego provider freemyip.com

### ISSUE THREAD

**Issue by tam481** [traefik/traefik#8407]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Hello,
I would be grateful if you could expand the Lego support to include freemyip.com as a supported provider.

Thank you in advane

**Comment by ldez** [comment]
Hello,

This kind of request must be done on the [lego](https://github.com/go-acme/lego/) repository.

But in this case, you are lucky because the issue already exists: https://github.com/go-acme/lego/issues/1450
And the implementation also: https://github.com/go-acme/lego/pull/1451

When a new release of lego will happen, we will update Traefik to support this DNS provider.
