### ISSUE TITLE
Filter (exclude) Access Logs by ClientAddr field

### ISSUE THREAD

**Issue by sgohl** [traefik/traefik#8459]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

According to https://doc.traefik.io/traefik/observability/access-logs/#filtering
the possible filters are only `statusCodes`, `retryAttempts`, `minDuration`

I would like to request the `ClientAddr` to be filterable also, because I am generating GoAccess stats from the Traefik Access Logs, and internal IPs are tistorting the reports, like in visit count etc..
Currently the reports would include any healthchecks from monitoring systems, the traefik Dashboard, etc.

Or, to make it ultimatively flexible, filter by a custom header (f.e. user-agent) with defined content. This way, I'd be in charge for setting the header at HAProxy before, for example. And any further needs from anyone would be mostly accomplished with that

**Comment by sgohl** [comment]
uff ... I think I misunderstood the filters the complete opposite way. 
I actually want to filter so that they will **not** be logged.

That ain't possible in any way, right?

**Comment by mpl** [comment]
Right.

**Comment by sgohl** [comment]
then I'd change the Feature Request to: implement Exclude-Filter

**Comment by rtribotte** [comment]
Hello @sgohl,

The ability to negate the filter is something else, and it is preferable to only track the addition of the ClientAddr field to the set of the filterable fields with this issue. This is why I have reworded the title.

In fact, we wouldn't accept a new filter operating by exclusion, since it wouldn't be consistent with the rest of the existing filters.
Moreover, as to how it is implemented now (e.g: the filters are each configurable via a dedicated configuration option), enabling them to work by exclusion is not trivial to fulfill complex scenarios.
It is an interesting idea, but it requires discussions around possible solutions in a dedicated issue.

Would you mind opening a new issue for the negation/exclusion mode of the access log filters?

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
