### ISSUE TITLE
Use Cloudflare's Cf-Connecting-Ip header as X-Real-IP

### ISSUE THREAD

**Issue by sylr** [traefik/traefik#8497]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I'd like Traefik to set `X-Real-IP` header to the value of [`Cf-Connecting-Ip`](https://support.cloudflare.com/hc/en-us/articles/200170786-Restoring-original-visitor-IPs#JUxJSMn3Ht5c5yq) if the remote IP is trusted.

**Comment by tomMoulard** [comment]
As mentioned in issue #3097, the `X-Real-Ip` behaviour is neither reliable nor well-documented, and it cannot be considered a de-facto standard (unlike `X-Forwarded-For`).

The current Traefik behaviour regarding how X-Real-Ip is handled is simple and limited on purpose but avoids security issues: if the request IP was trusted, it passes the header untouched and otherwise sets it with the request IP itself.

As this subject is not as easy as it could seem, we think that a better approach is to implement a [plugin](https://doc.traefik.io/traefik/v2.5/plugins/#plugins), which we can use as a prototype to gather feedback on the limitations of this feature, and gauge its popularity with the community.

As a side note, there is a [plugin](https://github.com/tomMoulard/htransformation) that can help you set the value of `X-Real-Ip` using the value of `Cf-Connecting-Ip`.
