### ISSUE TITLE
Possible error in documentation

### ISSUE THREAD

**Issue by tobiasb** [traefik/traefik#8558]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

According to https://github.com/traefik/traefik/blob/master/docs/content/middlewares/http/retry.md the retry middleware is enabled in the case of Docker discovery via the label `traefik.http.middlewares.test-retry.retry.attempts=4`

### What did you see instead?

I got an error in the logs saying

```
time="2021-11-05T22:54:33Z" level=error msg="middleware \"retry4@docker\" does not exist" entryPointName=web-secure routerName=my_service@docker
```

### What version of Traefik are you using?

```
docker exec traefik_traefik_1 traefik version
Version:      2.5.2
Codename:     livarot
Go version:   go1.17
Built:        2021-09-02T15:07:43Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by kevinpollet** [comment]
Hello @tobiasb and thanks for your interest in Traefik,

We just checked and everything is working fine. It seems that your issue is related to a configuration issue and the GitHub issue tracker is dedicated to bug and feature requests.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.

**Comment by tobiasb** [comment]
That's odd. I had to add the middleware via `traefik.http.middlewares.retry4.retry.attempts=4` because that's what I read somewhere, not `traefik.http.middlewares.test-retry.retry.attempts=4` for the error to go away.

**Comment by kevinpollet** [comment]
That's because `retry4` is the name of the middleware and `test-retry` is just an arbitrary name. The following error says that the middleware named `retry4` is not found.

`time="2021-11-05T22:54:33Z" level=error msg="middleware \"retry4@docker\" does not exist" entryPointName=web-secure routerName=my_service@docker`

**Comment by tobiasb** [comment]
I'm still not sure what the label should be for it to successfully set up the retry middleware. Is `test-retry` here  supposed to identify the service or router maybe? Do I have to explicitly add the middleware somewhere else?

**Comment by tobiasb** [comment]
I just found https://doc.traefik.io/traefik/middlewares/http/overview/ so I'll try something like this:

```
    - "traefik.http.middlewares.my-retry.retry.attempts=4"
    - "traefik.http.routers.my-router.middlewares=my-retry@docker
```
