### ISSUE TITLE
Enhance access log filtering 

### ISSUE THREAD

**Issue by betolink** [traefik/traefik#8758]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Right now, the access log can be filtered using statusCodes, retryAttempts and minDuration; it would be very handy to add more of the current supported fields and be able to customize the logic. This way we could setup filters that would do things like:

Log errors from a given IP range:  `ClientHost: (1.0.0.1, 191.255.255.254) && statusCodes(500)`
or
Exclude internal traffic (see  #6861): `! RouterName: (prometheus@internal, portainer@docker) `

I think this would be possible by refactoring [keepAccessLog](https://github.com/traefik/traefik/blob/31a5f3591f278aeeccaee9de530c109c14544ab8/pkg/middlewares/accesslog/logger.go#L357)

**Comment by noftaly** [comment]
I also propose filtering by `request_method`! I'd like to exclude all `OPTIONS` request for example, as my api is not on the same origin as my client, so my logs are flooded with `OPTIONS` requests.

**Comment by sgreiner** [comment]
We would also like to exclude specific requests of specific user agents or client IPs from the access log.
Throwing them away later in Elastic/Logstash increases latency and slows down log aggregation.

**Comment by nhuray** [comment]
Hi dear community, any news on that issue ? 

It would be very useful to have more capability for filtering logs based on routers, path,  http methods...

But I think the main blocker for most of the Traefik users is not be able to filter out logs for administrative routers like `ping` and `metrics`. Considering Kubernetes probes, load balancers and prometheus are using those routers, Traefik users does not have choice to **disable** completely access logs at the moment.

**Comment by nhuray** [comment]
@ldez @emilevauge Could we consider that issue in the coming Traefik versions ?

It's a blocker for most of the Kubernetes users cause the probes generate too much dummy logs.

**Comment by ddtmachado** [comment]
Hi @nhuray , we recently [declined a PR](https://github.com/traefik/traefik/pull/9205) that proposed adding a filtering mechanism to the access logs, mainly for performance reasons but of course it would also increase the maintenance and support complexity.

I'm mentioning that because while closing the PR we mentioned there might be better ways to solve the real problem people are complaining about, which really is to get rid of the internal routers on the access logs, such as the `ping` and `metrics`, and with that the team fully agrees.

For those reasons I'm closing this proposal in favor of [6861](https://github.com/traefik/traefik/issues/6861) which should deal with filtering internal routers only from the access logs.
