### ISSUE TITLE
Middleware/Service - Device authentication

### ISSUE THREAD

**Issue by averon420** [traefik/traefik#8769]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

Hello Traefik Team,

I wonder if it's possible to add a device authentication as a middleware. I mean, whenever a device starts a connection, some static and unique information are delivered. Therefor, you could create a fingerprint with these data and whitelist those to filter access to a service?
This would be a solution to have devices authenticated, where things like IP whitelist or user/password login aren't available.

**Comment by rtribotte** [comment]
Hello @averon420,

Thanks for your interest in Traefik!

Can you describe more precisely what would achieve this piece of TCP middleware?

**Comment by averon420** [comment]
Hey @rtribotte,

Sure, like when you have weak (no additional security, like bruteforce protection etc)  **HTTP** services accessible via traefik, you can further protect them with things like authelia. But if you plan to access this service via a mobile app. Like nextcloud, you simply cannot use authelia, since the mobile app is not able to authenticate via authelia.

My (maybe dumb) idea is, if it's possible to have a middleware, creating a unique fingerprint of each device trying to access a service and list those in a config file, or a simple website. You can simply whitelist those fingerprints to allow those devices, who should have access, the others get blocked by default. 

I came up with this, since, it's not always possible to whitelist IP address, if they are often changing (mobile network of phones, home networks with dynamic IP address). It's also not always possible to use a private VPN, since not all devices support that, and it's unhandy.

**Comment by rtribotte** [comment]
Hello @averon420,

Thanks for the clarification.

From what I can understand, you are proposing an HTTP middleware and not a TCP middleware.
Regarding this matter, maybe your proposal is a good candidate to build a [plugin middleware](https://pilot.traefik.io/plugins).
Please take a look at the https://github.com/traefik/plugindemo repository which is the place to start to build a plugin.
You can take advantage of the [local mode](https://github.com/traefik/plugindemo#local-mode) to play around.

Thus, it seems that the fingerprint you are mentioning should be produced by the application on the device. Because, as long as the request handled by Traefik would not have something specific to a device, it seems not possible to identify a device inside a middleware just by analyzing the request (computing a fingerprint). WDYT?

So, I'm wondering if the best way, to handle the scenario you are describing, would not be to have a specific header on the request (added by the application) to identify that device. Then you should be able to handle the device requests specifically either with routing configuration or a plugin.

**Comment by averon420** [comment]
Thanks for the quick response.

Well, yeah it should be an HTTP middleware and I can not modify the application. My idea was, since it's a http/https connection of the app to the service, through traefik. It sounds like a browser-like connection. AFAIK browsers got a fingerprint. So couldn't that be used to have an authentication based on that fingerprint? 

It's okay, if that's not possible. Thought its worth a try.

**Comment by rtribotte** [comment]
I have no knowledge about fingerprints relying only on the values of some headers on the request (e.g. `User-Agent`), and I was maybe wrong affirming that the fingerprinting should take place on client-side.

Nevertheless, this use case seems too edgy to be addressed as a core middleware, and I will decline your proposal for that reason.

But as I already mentioned, please take a look at our plugin system, which would allow you to achieve this feature.
