### ISSUE TITLE
No TLS 1.2 EMS Support

### ISSUE THREAD

**Issue by ryanhagen** [traefik/traefik#8853]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you expect to see?

I expect traefik TLS 1.2 to use extended master secrets by default with a toggle to turn them off. I can not find any proof that it does. Why doesn't it?
https://datatracker.ietf.org/doc/html/rfc7627

**Comment by mpl** [comment]
@ryanhagen traefik relies on the Go stdlib for TLS (notably https://pkg.go.dev/crypto/tls) , and even though I have yet to look deeper into the question I would be surprised if the stdlib didn't support extended master secrets by default. Especially since Adam Langley is involved in the Go stdlib and he's one of the authors of that RFC.

In any case, if I understand correctly https://www.rfc-editor.org/rfc/rfc8446.html#appendix-D (last paragraph) , TLS 1.3 does not even have extended master secrets anymore, because it intrinsically solved that particular MITM problem in another way. So I'd say if you want to be absolutely certain for now, just use TLS 1.3 on both the client side and server side.

**Comment by ryanhagen** [comment]
I've updated the issue to support EMS by default in tls1.2.

**Comment by Neustradamus** [comment]
To follow

**Comment by mmatur** [comment]
Hi,

We are still waiting for a fix upstream on https://github.com/golang/go/issues/43922

**Comment by mmatur** [comment]
A fix has been implemented [upstream](https://github.com/golang/go/issues/43922#issuecomment-1821167615). 

Closing this issue accordingly
