### ISSUE TITLE
consulcatalog.watch out of sync after network partition

### ISSUE THREAD

**Issue by nivekuil** [traefik/traefik#8948]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.containo.us) and didn't find any.

### What did you do?

Testing the new consul watch feature in 2.7.0. The consul agent traefik talks to has a network partition, I see this in traefik logs

```
{"@level":"error","@message":"Watch errored","@module":"consulcatalog.watch","@timestamp":"2022-04-18T17:59:13.569691Z","error":"Unexpected response code: 500 (rpc error getting client: failed to get conn: rpc error: lead thread didn't get connection)","retry":5000000000,"type":"services"}
{"@level":"error","@message":"Watch errored","@module":"consulcatalog.watch","@timestamp":"2022-04-18T17:59:18.570942Z","error":"Unexpected response code: 500 (Raft leader not found in server lookup mapping)","retry":20000000000,"type":"checks"}
```

an error here is expected (or not, since I have `consulcatalog.stale` set -- even a leaderless server should be able to respond?), but I expect traefik to handle it properly and retry until consul comes back up. Before, without watch, Traefik would just poll again and remain in sync with consul.

### What did you see instead?

The network partition is then fixed but Traefik's list of services is out of sync from consul's services and never catches up. I have to restart Traefik to re-synchronize consul catalog with Traefik's configuration.

### What version of Traefik are you using?

```
Version:      2.7.0-rc2
Codename:     epoisses
Go version:   go1.17.8
Built:        2022-03-29T15:07:48Z
OS/Arch:      linux/amd64
```

### What is your environment & configuration?
running in podman, relevant config:
```
                    "providers.consulcatalog.exposedByDefault"        false
                    "providers.consulcatalog.refreshInterval"         "1s"
                    "providers.consulcatalog.stale"                   true
                    "providers.consulcatalog.watch"                   true
                    "providers.consulcatalog"                         true
```

**Comment by kevinpollet** [comment]
Hello @nivekuil,

Thanks for your interest in Traefik,

After looking again at the implementation, the error logs come from the [consul](https://github.com/hashicorp/consul) client which is retrying to reconnect instead of raising an error, and not from Traefik.

The watch feature only changes the trigger mechanism used to discover the consul catalog services (an event in watch mode instead of a timer in poll mode) but the code for the service discovery remains the same. Thus, we are suspecting that something is wrong with the consul client.

To help us diagnose the issue, could you provide a reproducible use case?

**Comment by nivekuil** [comment]
Yes, the consul agent has experienced a network partition. With polling Traefik will emit an error and then retry, but it looks like there isn't retry logic with watch.

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).

**Comment by ddtmachado** [comment]
@nivekuil the bot closed the issue for lack of activity since we didn't receive the feedback on the reproducible use case.

Still I want to clarify why we didn't reopen it, we believe the problem lies in the consul library and not in Traefik directly but without a reproducible use case we can't really point out where in the consul code the problem might be.

If you still experience this problem try looking for similar issue on the [consul repository](https://github.com/hashicorp/consul) or asking about it if there is nothing similar already, you can even link this Traefik issue on the post if needed.

**Comment by svenstaro** [comment]
We have the same problem and I think the bug should be re-opened. This seems like a fairly important issue. Essentially the `watch = true` mode of `providers.consulCatalog` effectively becomes useless and so Consul watch mode can't be used at all if it's this finicky. We've gone back to aggressive polling and it seems to work fine for the time being.
