### ISSUE TITLE
Does accessControlAllowMethods work properly?

### ISSUE THREAD

**Issue by jankohout95** [traefik/traefik#8966]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I am opening this issue one more time because it was closed via traefik bot. (https://github.com/traefik/traefik/issues/8965)
And it looks like accessControlAllowMethods does not work properly

I am wondering if accessControlAllowMethods should block unexpected http methods in request header.
For example, when there is a request method `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA`, Traefik passes that through in a specific route and the request is handled in the endpoint of that specific route.

This issue/question is published in chain to my previous one (https://github.com/traefik/traefik/issues/8961) since response header contains allowed methods for a request with `OPTIONS` method (probably my lack of information about CORS), but accessControlAllowMethods does not restrict requests for non-matching methods.

### What did you see instead?

By another words I specified only methods `accessControlAllowMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]`, but it even returned response `["GET", "HEAD", "OPTIONS"]` for my `OPTIONS` like request and when I make a request with `AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA` method, Traefik passes it through without throwing any error.
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/100849407/165030991-2b5fb319-a492-4b3a-94bd-864aa529f5a1.png">

As I was searching, the only post where it looked like, there is a provided kind of configuration is this, https://stackoverflow.com/questions/58012063/restrict-allowed-methods-on-traefik-routes, but as you can see in comment bellow, "And this would not block the requests with an incorrect HTTP method" 

**Desired state** is, Traefik should have some parameter which allows only listed methods and if request method does not match any of specified in a list, throws for ex. an error `405 Method Not Allowed` and does not pass request into specific route.

My final question is, does accessControlAllowMethods parameter restrict other methods except the specified in list, or does it have just informative purpose in OPTION like request? Is it a bug or feature? Should not it return in response all the methods, which were defined in list in configuration? Is there any other configuration which restricts access for unlisted methods?

### What version of Traefik are you using?

Version and environment is equal to specified in previous issue: https://github.com/traefik/traefik/issues/8961.

### What is your environment & configuration?

Version and environment is equal to specified in previous issue: https://github.com/traefik/traefik/issues/8961.

**Comment by jankohout95** [comment]
@jakubhajek any updates about this? :)

**Comment by jakubhajek** [comment]
Hello @jankohout95 

Thanks a lot for using Traefik and opening the issue. 

The headers `Access-Control-Allow-Methods` and `Access-Controll-Allow-Headers` are Cross-Origin Resource Sharing [(CORS) ](https://doc.traefik.io/traefik/middlewares/http/headers/#cors-headers)response-type headers. It is used to indicate which HTTP methods are permitted while accessing resources in response to the cross-origin requests.  Those headers work as expected based on the example provided in the previously created issue: #8961 

I think you are looking for the possibility to whitelist HTTP methods that will be accepted by Traefik. Let me give you an example, if the `allowedMethods` contains a list of `[GET, POST]`, the request sent using `PUT` method will not be processed by Traefik and the 405 HTTP response should be returned. 


The easiest way to achieve this is to create a router that contains for example HOST and Method matching rules with the list of allowed HTTP methods, here is the example:

``Host(`example.com`) && Method(`GET`, `POST`)``

By creating a router including that rule, Traefik will be matching Host and HTTP methods `GET ` or `POST`. For those conditions, incoming requests will be processed and passed to service. However, if a request arrives with e.g `PUT` method, Traefik will throw the 404 HTTP response because there is no router that matches the request criteria. 

You can learn more about available matchers by visiting that [link](https://doc.traefik.io/traefik/routing/routers/#rule). 

Please let us know if that solves the issue you raised.

**Comment by jankohout95** [comment]
Hey @jakubhajek many thanks for your answer! It works! (source: https://doc.traefik.io/traefik/routing/routers/)

But there are still unclear two things in that:

1. Why it returned only this in header response ["GET", "HEAD", "OPTIONS"] for OPTIONS request, when I explicitly specified this accessControlAllowMethods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]?

2. After setting up correct route rules (as you mentioned), Traefik returns (Status 405, method not allowed): 
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/100849407/166326179-04ffdfef-db22-4c19-b877-7caf39d01282.png">
I mean status code is much more clear as 405, so no complains. Just saying it is not 404. :)


TFYA :)

**Comment by traefiker** [comment]
Hi! I'm Træfiker :robot: the bot in charge of tidying up the issues.

I have to close this one because of its lack of activity :disappointed:

Feel free to re-open it or join our [Community Forum](https://community.containo.us/).
