### ISSUE TITLE
TLS passthrough and HostSNI rules for HTTP/3 UDP

### ISSUE THREAD

**Issue by cdauth** [traefik/traefik#9050]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I am using traefik on a host system to forward HTTPS requests to various traefik instances running in different VMs. The host system traefik uses TLS passthrough and SNI rules to forward the traffic, since it has only one public IP address. Each VM is administrated by different people, who take care of keeping their TLS keys up to date inside their VMs.

I would like to make the websites that are hosted inside my VMs available via HTTP/3. To do so, I have added `http3: {}` to the port 443 entryPoint on my host system traefik.

I would expect any incoming HTTP/3 requests to be forwarded to my VMs according to the `HostSNI` rules that I have configured. If at all technically possible, it would be good if the requests were forwarded to the VMs as HTTP/1.1 or HTTP/2 so that it works independently of which HTTP version the target server supports. Also, the proxy protocol should be used when enabled (and I'm not sure whether it works with HTTP/3 at all).

What I'm seeing instead with traefik 2.7.0 is that HTTP/3 requests made against the host system are answered with a 404 error.

As a workaround, I can set up one UDP port forward to port 443 of each VM, enable HTTP/3 on the VM traefik instances instead of the host system, and advertise the forwarded port using `http3.advertisedPort`. Unfortunately, my experiments have shown that Chrome only supports HTTP/3 on port 443. More details can be found here: https://community.traefik.io/t/tls-passthrough-with-http-3/14604

**Comment by mpl** [comment]
Hello,

Unfortunately, what you want to do (routing over SNI) is not possible at the moment if you need to do the TLS termination on the backends (the VMs). Because we would need to support DTLS (in order to be able to get the SNI information, and route accordingly), which we do not yet. Then, as far as traefik is concerned each of your routers would be UDP routers, with their own SNI routing rule. At the moment, there is no way for traefik to route UDP traffic according to an SNI rule.
If that is something you're interested in, you probably want to follow: https://github.com/traefik/traefik/issues/6642

Please note however, that if you were not constrained by passthrough (i.e. if your setup would allow for TLS termination on traefik), then you would probably be able to achieve the rest. Traefik would handle the incoming HTTP/3 traffic (so UDP in reality) but then under the scenes would handle it as HTTP (so TCP) and would be able to route it to the right backend. I know it's probably not an option for you, but maybe just something to keep in mind.

You're raising other distinct points in the issue that I'm not addressing because they seem moot as long as the first routing hurdle is not solved. But if you still feel like discussing them, please open an issue for each of them.

**Comment by cdauth** [comment]
Thank you for pointing me in the right direction. My knowledge of HTTP/3 is very superficial, so I had no idea what to even look for.

I am, however, still a bit confused. I cannot find much information online, but from the few resources that I could find that mention both HTTP/3 and DTLS in the same article, it sounds to me like while both specifications achieve TLS over UDP, HTTP/3 is not using DTLS to achieve this. So are you sure that implementing DTLS in traefik will enable me to do passthrough SNI routing for HTTP/3? Or maybe I'm misunderstanding something?

I could open a pull request that adds some clarifications about the details and limitations of HTTP/3 support to the documentation, would that be useful?
