### ISSUE TITLE
Improve throughput performance

### ISSUE THREAD

**Issue by ddtmachado** [traefik/traefik#9122]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

With the next major on the horizon we would love to study ways to improve the overall throughput performance of Traefik Proxy.

So far we have done some internal proof of concept projects involving a few different approaches / technologies. The most promising so far are:

- Replace net/http with [fasthttp](https://github.com/valyala/fasthttp)
- Use [eBPF](https://ebpf.io/) to offload part of the processing path

We want to centralize discussions around this topic here and welcome feedback and suggestions. More in depth details on what was already explored will be shared soon.

**Comment by bencehornak-gls** [comment]
What is the status of this ticket? I'm asking curiously, because this ticket has been in the 'Short Term' pipeline since 2022. I saw that it was decided to not ship fasthttp with v3 (https://github.com/traefik/traefik/pull/9528#issuecomment-1875574311), so I was wondering if v3 will see any performance gains over v2?

If so, is it planned to have some official benchmarks backing the improvements? I found only one article in this topic on Medium, in which the author concluded that as of writing the article (nearly a year ago) they weren't able to confirm the 20% performance gain.
https://medium.com/beyn-technology/is-nginx-dead-is-traefik-v3-20-faster-than-traefik-v2-f28ffb7eed3e

Looking forward to hearing more about this, this is the only argument my colleagues have against Traefik, otherwise we find it a much better fit for our use cases than nginx.

**Comment by emilevauge** [comment]
Quick status on this:
- The quoted blog post on the performance testing (https://medium.com/beyn-technology/is-nginx-dead-is-traefik-v3-20-faster-than-traefik-v2-f28ffb7eed3e) is innacurate as the author is using Docker images **that doesn't contain the merged PR**. Basically, he wasn't testing the fasthttp pipeline but the standard one. I even added a comment [to highlight the issue](https://medium.com/@emilevauge/hi-emre-6d307d9826eb), but the author simply ignored it...
- The team plans to merge & release fasthttp later this year :)

**Comment by STOCKZE** [comment]
will there be support for ebpf along side fasthttp in the milestone 3.0, considering the thread started with both mentions

**Comment by nmengin** [comment]
Hello @STOCKZE,

Thank you for reaching out.

There is no plan to bring EBPF support on the short term, the team is first focusing on bringing the FastHTTP integration.

**Comment by everflux** [comment]
Could this also fix this issue: https://github.com/traefik/traefik/issues/7465 ?

**Comment by nmengin** [comment]
According to my previous comment.

Closed by #11122.
