### ISSUE TITLE
mkcert certificatesResolver

### ISSUE THREAD

**Issue by loranger** [traefik/traefik#9173]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

I searched the web for a simple automation but failed so here I come, asking naively:

Wouldn't it be cool/Is there a way to use mkcert as a certificates resolver as we can achieve using letsencrypt ?
Defining a host would deal with the mkcert generation with the current domain if local cert does not exists.

Of course it would not provide the `mkcert -install` step which need to be executed locally root CA installation, but it's good for security

Personally, as a compulsive docker-compose spawner, I would love it 😍

**Comment by tomMoulard** [comment]
Hello @loranger,

Thanks for your interest in Traefik !

[`mkcert`](https://github.com/FiloSottile/mkcert) is a tool to make locally trusted development certificates, there is the [smallstep/step-ca](https://github.com/smallstep/certificates) project that allows to create local development certificates.
By using this service, you can create a new [`certificatesResolvers`](https://doc.traefik.io/traefik/https/acme/#certificate-resolvers), and, using the [`caServer`](https://doc.traefik.io/traefik/https/acme/#caserver) option, you can mimic Let's Encrypt behavior to generate locally trusted development certificates.
`step-ca` provide [an example](https://smallstep.com/docs/tutorials/acme-protocol-acme-clients#traefik) to run the service with Traefik.

As this issue is not related to traefik itself, we will close this issue.

Feel free to join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik section](https://community.traefik.io/c/traefik/5) to discuss this further if needed.
