### ISSUE TITLE
doc.traefik.io HTTPS certificate is invalid

### ISSUE THREAD

**Issue by jilleJr** [traefik/traefik#9176]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

Try access documentation page https://doc.traefik.io/

### What did you see instead?

Browser says "Warning: Potential Security Risk Ahead"

![image](https://user-images.githubusercontent.com/2477952/178216737-4f81fe4f-837d-4cb7-b9c1-84ab6bdfb203.png)

Apparently the certificate is only registered for the following names:

```
        Subject: C = US, ST = California, L = San Francisco, O = "GitHub, Inc.", CN = *.github.com
        ...
            X509v3 Subject Alternative Name:
                DNS:*.github.com, DNS:www.github.com, DNS:github.io, DNS:github.com, DNS:*.github.io, DNS:githubusercontent.com, DNS:*.githubusercontent.com
```

It needs to be registered for doc.traefik.io as well.
This is probably just a misconfiguration in this repo's GitHub Pages settings

### What version of Traefik are you using?

N/A

### What is your environment & configuration?

N/A

### If applicable, please paste the log output in DEBUG level

N/A

**Comment by mmatur** [comment]
Hi @jilleJr,

Thanks for reaching out, the issue was due to the migration from netlify to Github pages for the documentation. 

Github had to generate a new certificate for `doc.traefik.io` and deploy this certificate to their infrastructure. Following their [documentation](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#troubleshooting-certificate-provisioning-certificate-not-yet-created-error) this process can take several minutes to complete. 

Now the certificate is available globally and there is no more issue.

I'm closing this issue.

Thanks
