### ISSUE TITLE
Kubernetes Gateway API v1beta1

### ISSUE THREAD

**Issue by ddtmachado** [traefik/traefik#9476]
Epic to track progress on issues and blockers for supporting the full v1beta1 Gateway API spec

[Spec Reference](https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1beta1)

This issue should also be used to hold discussions on the implementation proposals / plans

Linked issues:

- https://github.com/traefik/traefik/issues/8705
- https://github.com/traefik/traefik/issues/9471

**Comment by ttys3** [comment]
we also need "Cross-Namespace routing" support, otherwise the gateway provider is useless

https://github.com/traefik/traefik/blob/519ed8bde58e9ebc6d9618a38a351208820cf273/pkg/provider/kubernetes/gateway/kubernetes.go#L1443

https://gateway-api.sigs.k8s.io/guides/multiple-ns/

https://github.com/kubernetes-sigs/gateway-api/blob/main/site-src/geps/gep-709.md#L7
