### ISSUE TITLE
[Metrics] Add the traffic source as label in metrics

### ISSUE THREAD

**Issue by elghazal-a** [traefik/traefik#9516]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

This a feature request.

Actually, we use Traefik in Kubernetes for service-to-service communication, so we have metrics for all traffic going to all services. However, we'd love to filter metrics by traffic source. 

I would like to request this feature:

* Add an additional label called `source` that will contain the source of traffic. It can be a pod name in K8s context, container name in the context of Docker, service name in the context consul or just an IP address in case Traefik couldn't match the IP with a name, etc..

**Comment by rtribotte** [comment]
Hello @elghazal-a,

Thanks for your interest in Traefik!

Have you tried to leverage the Tracing? It seems more adapted for such a use case. The Traefik service name is added to every span.
Nonetheless, we think that it is not achievable in most cases, because it would be too difficult for Traefik to identify the pod/container/service name.

Accordingly, we are declining this proposal, but feel free to ask to re-open it if you think that we are missing something here.
