### ISSUE TITLE
ipWhiteList

### ISSUE THREAD

**Issue by flyhigh-hifi** [traefik/traefik#9646]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I've got broken middleware - ipWhiteList while testing new beta version of traefik with namespaceS supported just because one guy decided that can contribute to open source just using Find and Replace button in text editor. What is wrong with this word? Can someone explain why such commits are taken into master branch? I have searched through issues and didn't see any mention of it, especially insulting someone who asked to rename it. It's a common term in computer science - [white list](https://en.wikipedia.org/wiki/Whitelist), just like blue sky or red roses or black box.

I don't like **ipa**llowlist because i'm starting to think about getting drunk right on my job with India Pale Ale beer every time I see my traefik config. Reasonable, right?

https://github.com/traefik/traefik/commit/1b9873cae990cf446584f08299fd91037d3e2117

### What did you see instead?

field not found, node: ipWhiteList

### What version of Traefik are you using?

3.0.0.-beta2

### What is your environment & configuration?

```yaml
# (paste your configuration here)
```

Add more configuration information here.

**Comment by 16g** [comment]
👍👍👍

**Comment by yanislav-igonin** [comment]
👍👍👍
meh, another kid insulted by the computer science term
pain in the ass was burning so high that the only decision was to change EVERY word that contains WHITE in the codebase

**Comment by migs35323** [comment]
:+1: 

a few minutes of silence for all the IDE hard drives that got mad and forced github/gitlab to drop the default name of master branches

**Comment by tfny** [comment]
Hey, thanks for bringing this up.  Unexpected work is frustrating and I am sorry for the inconvenience.
 
We've heard both sides of this and we chose to use allowlist and denylist because, as a global company with an increasingly diverse work environment, the request to move to a more inclusive naming convention is simple and reflects our values of inclusivity.

While, to your point, ‘white list’ and ‘black list’ are common terms, we feel ‘allow’ and ‘deny’ make the meaning of the list more clear no matter a user’s language, educational, or cultural background.

That said, there is a silver lining in knowing what beverage to have when you celebrate being done with work this evening. :)
