### ISSUE TITLE
Geoblocking

### ISSUE THREAD

**Issue by joeldeteves** [traefik/traefik#9665]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

We would like to see a built-in Geoblocking middleware maintained by the Traefik team.

I understand there are plugins available from the community, however they're liable to stop being maintained, break during major version upgrades e.g. the upcoming v3 release, etc.

Now that Traefik has IP Blacklisting support this seems like a natural extension of that and something that would add even more value in terms of Traefik's "ease-of-use"

As the bulk of spam traffic comes from a handful of countries this would be a great feature.

Thanks for your consideration,

**Comment by rtribotte** [comment]
Hello @joeldeteves,

After some discussions about this, we think that supporting a GeoIP IP feature in the Traefik would be a consequent additional work, and also that it doesn't fit well with the core of Traefik because we don't want it to be tied to third parties specificities.
In this case, it is because it would require supporting sourcing from different third parties, GeoIP databases, or lookup services.

We also think that today the plugin mechanism is a great alternative to bring GeoIP support to Traefik and that, in a more "hacky" way, the `ForwardAuth` middleware could be leveraged as well.

We completely understand the use case, but for those reasons, we think this feature has very few little chances to be added to the core of Traefik someday.

Nonetheless, thank you for this contribution.
We want to keep the proposal open to see how much it gets traction, but there is already the issue https://github.com/traefik/traefik/issues/4868, which seems to cover enough of the same need. Accordingly, we are closing this one in benefit of the #4868 
Thanks f
