### ISSUE TITLE
[Feature Request] Do not serve "TRAEFIK DEFAULT CERT" when a certificate exists

### ISSUE THREAD

**Issue by lonix1** [traefik/traefik#9945]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you expect to see?

Even when a valid certificate is available, traefik serves the "TRAEFIK DEFAULT CERT". Setting `sniStrict: true` does [not solve](https://community.traefik.io/t/common-tls-config-for-all-services/18884/10) the problem (and in some cases is undesirable).

There is an old [issue](https://github.com/traefik/traefik/issues/5849) related to this, but it was closed by a bot without resolution.

Please consider adding an optional switch so we can disable this behaviour? It's not useful in production. It could error/warn when no certificate is usable for a route.

**Comment by rtribotte** [comment]
Hello @lonix1,

Thanks for reporting this!

It looks like the default certificate configuration on the TLS store would help in your situation, please take a look at this [documentation](https://doc.traefik.io/traefik/https/tls/#default-certificate).

It seems that your issue is related to a configuration issue and the GitHub issue tracker is dedicated to bug and feature requests.

For help on your configuration, please join our [Community Forum](https://community.traefik.io/) and reach out to us on the [Traefik v2 section](https://community.traefik.io/c/traefik/traefik-v2). 

We will close this issue accordingly but feel free to re-open it if you think that we missed something.

**Comment by rtribotte** [comment]
Hello @lonix1,

Sorry, I overlooked that you already knew of the default certificate configuration.

Regarding the `strictSNI` option, what you are experiencing seems almost impossible.

The following code is the part involving this option:
https://github.com/traefik/traefik/blob/878e7de56a875ccb09d05d61d4ffc3e2e22eda87/pkg/tls/tlsmanager.go#L206-L210

As you can see if no certificate matches, no one is returned and the connection will be closed, so there are no chances to serve the default certificate.

It makes me think that you are still facing a configuration issue.

**Comment by rtribotte** [comment]
We suspect that the TLSOption which was chosen to serve the connection doesn't have the `strictSNI` option to `true`.
Can you please make sure that each of the TLSOptions configures the `strictSNI` option to `true`? (Including the `default` one)

**Comment by rtribotte** [comment]
Hello @lonix1,

Can you try to configure as well the default TLS option?

The default TLSOption configured on a router is only used when a router has a host rule that can be leveraged to match with the router TLSOption configuration when doing the TLS handshake.
For instance, a router with a `HostRegexp` or a `PathPrefix` rule only cannot satisfy its TLSOption configuration and would always fall back with the default one.
In those cases, during route build time, you should be able to see a warning log like below:
```
No domain found in rule %v, the TLS options applied for this router will depend on the SNI of each request
```
