### ISSUE TITLE
Not able to redirect http to https while using nlb behind traefik

### ISSUE THREAD

**Issue by tgamAnkur** [traefik/traefik#9948]
### Welcome!

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/traefik/traefik/issues) and didn't find any.
- [X] Yes, I've searched similar issues on the [Traefik community forum](https://community.traefik.io) and didn't find any.

### What did you do?

I want to  redirect all traffic from http to https

### What did you see instead?

when i configure the middleware, infinite requests are been called and returns me 301 error

### What version of Traefik are you using?

2.6.1

### What is your environment & configuration?

    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:us-east-1:*:certificate/*
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
    service.beta.kubernetes.io/aws-load-balancer-access-log-emit-interval: "5"
    service.beta.kubernetes.io/aws-load-balancer-access-log-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-name: ""
    service.beta.kubernetes.io/aws-load-balancer-access-log-s3-bucket-prefix: ""

**Comment by nmengin** [comment]
Hello @tgamAnkur,

Thanks for reaching out!

Your problem seems to be linked to a configuration issue.
To keep the repository focused, we ask that all questions be asked in the [community forum] (https://community.traefik.io/).

It is pretty active, so you might find that your question has already been answered there.  If not, you can ask and get help from other community members pretty quickly.
